// Code generated by ent, DO NOT EDIT.

package ticket

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"kv-shepherd.io/shepherd/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldUpdatedAt, v))
}

// EventID applies equality check predicate on the "event_id" field. It's identical to EventIDEQ.
func EventID(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldEventID, v))
}

// Requester applies equality check predicate on the "requester" field. It's identical to RequesterEQ.
func Requester(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldRequester, v))
}

// Approver applies equality check predicate on the "approver" field. It's identical to ApproverEQ.
func Approver(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldApprover, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldReason, v))
}

// RejectReason applies equality check predicate on the "reject_reason" field. It's identical to RejectReasonEQ.
func RejectReason(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldRejectReason, v))
}

// SelectedClusterID applies equality check predicate on the "selected_cluster_id" field. It's identical to SelectedClusterIDEQ.
func SelectedClusterID(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldSelectedClusterID, v))
}

// SelectedStorageClass applies equality check predicate on the "selected_storage_class" field. It's identical to SelectedStorageClassEQ.
func SelectedStorageClass(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldSelectedStorageClass, v))
}

// ParentTicketID applies equality check predicate on the "parent_ticket_id" field. It's identical to ParentTicketIDEQ.
func ParentTicketID(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldParentTicketID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldUpdatedAt, v))
}

// EventIDEQ applies the EQ predicate on the "event_id" field.
func EventIDEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldEventID, v))
}

// EventIDNEQ applies the NEQ predicate on the "event_id" field.
func EventIDNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldEventID, v))
}

// EventIDIn applies the In predicate on the "event_id" field.
func EventIDIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldEventID, vs...))
}

// EventIDNotIn applies the NotIn predicate on the "event_id" field.
func EventIDNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldEventID, vs...))
}

// EventIDGT applies the GT predicate on the "event_id" field.
func EventIDGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldEventID, v))
}

// EventIDGTE applies the GTE predicate on the "event_id" field.
func EventIDGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldEventID, v))
}

// EventIDLT applies the LT predicate on the "event_id" field.
func EventIDLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldEventID, v))
}

// EventIDLTE applies the LTE predicate on the "event_id" field.
func EventIDLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldEventID, v))
}

// EventIDContains applies the Contains predicate on the "event_id" field.
func EventIDContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldEventID, v))
}

// EventIDHasPrefix applies the HasPrefix predicate on the "event_id" field.
func EventIDHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldEventID, v))
}

// EventIDHasSuffix applies the HasSuffix predicate on the "event_id" field.
func EventIDHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldEventID, v))
}

// EventIDEqualFold applies the EqualFold predicate on the "event_id" field.
func EventIDEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldEventID, v))
}

// EventIDContainsFold applies the ContainsFold predicate on the "event_id" field.
func EventIDContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldEventID, v))
}

// OperationTypeEQ applies the EQ predicate on the "operation_type" field.
func OperationTypeEQ(v OperationType) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldOperationType, v))
}

// OperationTypeNEQ applies the NEQ predicate on the "operation_type" field.
func OperationTypeNEQ(v OperationType) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldOperationType, v))
}

// OperationTypeIn applies the In predicate on the "operation_type" field.
func OperationTypeIn(vs ...OperationType) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldOperationType, vs...))
}

// OperationTypeNotIn applies the NotIn predicate on the "operation_type" field.
func OperationTypeNotIn(vs ...OperationType) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldOperationType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldStatus, vs...))
}

// RequesterEQ applies the EQ predicate on the "requester" field.
func RequesterEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldRequester, v))
}

// RequesterNEQ applies the NEQ predicate on the "requester" field.
func RequesterNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldRequester, v))
}

// RequesterIn applies the In predicate on the "requester" field.
func RequesterIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldRequester, vs...))
}

// RequesterNotIn applies the NotIn predicate on the "requester" field.
func RequesterNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldRequester, vs...))
}

// RequesterGT applies the GT predicate on the "requester" field.
func RequesterGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldRequester, v))
}

// RequesterGTE applies the GTE predicate on the "requester" field.
func RequesterGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldRequester, v))
}

// RequesterLT applies the LT predicate on the "requester" field.
func RequesterLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldRequester, v))
}

// RequesterLTE applies the LTE predicate on the "requester" field.
func RequesterLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldRequester, v))
}

// RequesterContains applies the Contains predicate on the "requester" field.
func RequesterContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldRequester, v))
}

// RequesterHasPrefix applies the HasPrefix predicate on the "requester" field.
func RequesterHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldRequester, v))
}

// RequesterHasSuffix applies the HasSuffix predicate on the "requester" field.
func RequesterHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldRequester, v))
}

// RequesterEqualFold applies the EqualFold predicate on the "requester" field.
func RequesterEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldRequester, v))
}

// RequesterContainsFold applies the ContainsFold predicate on the "requester" field.
func RequesterContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldRequester, v))
}

// ApproverEQ applies the EQ predicate on the "approver" field.
func ApproverEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldApprover, v))
}

// ApproverNEQ applies the NEQ predicate on the "approver" field.
func ApproverNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldApprover, v))
}

// ApproverIn applies the In predicate on the "approver" field.
func ApproverIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldApprover, vs...))
}

// ApproverNotIn applies the NotIn predicate on the "approver" field.
func ApproverNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldApprover, vs...))
}

// ApproverGT applies the GT predicate on the "approver" field.
func ApproverGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldApprover, v))
}

// ApproverGTE applies the GTE predicate on the "approver" field.
func ApproverGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldApprover, v))
}

// ApproverLT applies the LT predicate on the "approver" field.
func ApproverLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldApprover, v))
}

// ApproverLTE applies the LTE predicate on the "approver" field.
func ApproverLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldApprover, v))
}

// ApproverContains applies the Contains predicate on the "approver" field.
func ApproverContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldApprover, v))
}

// ApproverHasPrefix applies the HasPrefix predicate on the "approver" field.
func ApproverHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldApprover, v))
}

// ApproverHasSuffix applies the HasSuffix predicate on the "approver" field.
func ApproverHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldApprover, v))
}

// ApproverIsNil applies the IsNil predicate on the "approver" field.
func ApproverIsNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldIsNull(FieldApprover))
}

// ApproverNotNil applies the NotNil predicate on the "approver" field.
func ApproverNotNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldNotNull(FieldApprover))
}

// ApproverEqualFold applies the EqualFold predicate on the "approver" field.
func ApproverEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldApprover, v))
}

// ApproverContainsFold applies the ContainsFold predicate on the "approver" field.
func ApproverContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldApprover, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldReason, v))
}

// RejectReasonEQ applies the EQ predicate on the "reject_reason" field.
func RejectReasonEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldRejectReason, v))
}

// RejectReasonNEQ applies the NEQ predicate on the "reject_reason" field.
func RejectReasonNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldRejectReason, v))
}

// RejectReasonIn applies the In predicate on the "reject_reason" field.
func RejectReasonIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldRejectReason, vs...))
}

// RejectReasonNotIn applies the NotIn predicate on the "reject_reason" field.
func RejectReasonNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldRejectReason, vs...))
}

// RejectReasonGT applies the GT predicate on the "reject_reason" field.
func RejectReasonGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldRejectReason, v))
}

// RejectReasonGTE applies the GTE predicate on the "reject_reason" field.
func RejectReasonGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldRejectReason, v))
}

// RejectReasonLT applies the LT predicate on the "reject_reason" field.
func RejectReasonLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldRejectReason, v))
}

// RejectReasonLTE applies the LTE predicate on the "reject_reason" field.
func RejectReasonLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldRejectReason, v))
}

// RejectReasonContains applies the Contains predicate on the "reject_reason" field.
func RejectReasonContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldRejectReason, v))
}

// RejectReasonHasPrefix applies the HasPrefix predicate on the "reject_reason" field.
func RejectReasonHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldRejectReason, v))
}

// RejectReasonHasSuffix applies the HasSuffix predicate on the "reject_reason" field.
func RejectReasonHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldRejectReason, v))
}

// RejectReasonIsNil applies the IsNil predicate on the "reject_reason" field.
func RejectReasonIsNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldIsNull(FieldRejectReason))
}

// RejectReasonNotNil applies the NotNil predicate on the "reject_reason" field.
func RejectReasonNotNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldNotNull(FieldRejectReason))
}

// RejectReasonEqualFold applies the EqualFold predicate on the "reject_reason" field.
func RejectReasonEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldRejectReason, v))
}

// RejectReasonContainsFold applies the ContainsFold predicate on the "reject_reason" field.
func RejectReasonContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldRejectReason, v))
}

// SelectedClusterIDEQ applies the EQ predicate on the "selected_cluster_id" field.
func SelectedClusterIDEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldSelectedClusterID, v))
}

// SelectedClusterIDNEQ applies the NEQ predicate on the "selected_cluster_id" field.
func SelectedClusterIDNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldSelectedClusterID, v))
}

// SelectedClusterIDIn applies the In predicate on the "selected_cluster_id" field.
func SelectedClusterIDIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldSelectedClusterID, vs...))
}

// SelectedClusterIDNotIn applies the NotIn predicate on the "selected_cluster_id" field.
func SelectedClusterIDNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldSelectedClusterID, vs...))
}

// SelectedClusterIDGT applies the GT predicate on the "selected_cluster_id" field.
func SelectedClusterIDGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldSelectedClusterID, v))
}

// SelectedClusterIDGTE applies the GTE predicate on the "selected_cluster_id" field.
func SelectedClusterIDGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldSelectedClusterID, v))
}

// SelectedClusterIDLT applies the LT predicate on the "selected_cluster_id" field.
func SelectedClusterIDLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldSelectedClusterID, v))
}

// SelectedClusterIDLTE applies the LTE predicate on the "selected_cluster_id" field.
func SelectedClusterIDLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldSelectedClusterID, v))
}

// SelectedClusterIDContains applies the Contains predicate on the "selected_cluster_id" field.
func SelectedClusterIDContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldSelectedClusterID, v))
}

// SelectedClusterIDHasPrefix applies the HasPrefix predicate on the "selected_cluster_id" field.
func SelectedClusterIDHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldSelectedClusterID, v))
}

// SelectedClusterIDHasSuffix applies the HasSuffix predicate on the "selected_cluster_id" field.
func SelectedClusterIDHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldSelectedClusterID, v))
}

// SelectedClusterIDIsNil applies the IsNil predicate on the "selected_cluster_id" field.
func SelectedClusterIDIsNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldIsNull(FieldSelectedClusterID))
}

// SelectedClusterIDNotNil applies the NotNil predicate on the "selected_cluster_id" field.
func SelectedClusterIDNotNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldNotNull(FieldSelectedClusterID))
}

// SelectedClusterIDEqualFold applies the EqualFold predicate on the "selected_cluster_id" field.
func SelectedClusterIDEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldSelectedClusterID, v))
}

// SelectedClusterIDContainsFold applies the ContainsFold predicate on the "selected_cluster_id" field.
func SelectedClusterIDContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldSelectedClusterID, v))
}

// SelectedStorageClassEQ applies the EQ predicate on the "selected_storage_class" field.
func SelectedStorageClassEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldSelectedStorageClass, v))
}

// SelectedStorageClassNEQ applies the NEQ predicate on the "selected_storage_class" field.
func SelectedStorageClassNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldSelectedStorageClass, v))
}

// SelectedStorageClassIn applies the In predicate on the "selected_storage_class" field.
func SelectedStorageClassIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldSelectedStorageClass, vs...))
}

// SelectedStorageClassNotIn applies the NotIn predicate on the "selected_storage_class" field.
func SelectedStorageClassNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldSelectedStorageClass, vs...))
}

// SelectedStorageClassGT applies the GT predicate on the "selected_storage_class" field.
func SelectedStorageClassGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldSelectedStorageClass, v))
}

// SelectedStorageClassGTE applies the GTE predicate on the "selected_storage_class" field.
func SelectedStorageClassGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldSelectedStorageClass, v))
}

// SelectedStorageClassLT applies the LT predicate on the "selected_storage_class" field.
func SelectedStorageClassLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldSelectedStorageClass, v))
}

// SelectedStorageClassLTE applies the LTE predicate on the "selected_storage_class" field.
func SelectedStorageClassLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldSelectedStorageClass, v))
}

// SelectedStorageClassContains applies the Contains predicate on the "selected_storage_class" field.
func SelectedStorageClassContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldSelectedStorageClass, v))
}

// SelectedStorageClassHasPrefix applies the HasPrefix predicate on the "selected_storage_class" field.
func SelectedStorageClassHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldSelectedStorageClass, v))
}

// SelectedStorageClassHasSuffix applies the HasSuffix predicate on the "selected_storage_class" field.
func SelectedStorageClassHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldSelectedStorageClass, v))
}

// SelectedStorageClassIsNil applies the IsNil predicate on the "selected_storage_class" field.
func SelectedStorageClassIsNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldIsNull(FieldSelectedStorageClass))
}

// SelectedStorageClassNotNil applies the NotNil predicate on the "selected_storage_class" field.
func SelectedStorageClassNotNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldNotNull(FieldSelectedStorageClass))
}

// SelectedStorageClassEqualFold applies the EqualFold predicate on the "selected_storage_class" field.
func SelectedStorageClassEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldSelectedStorageClass, v))
}

// SelectedStorageClassContainsFold applies the ContainsFold predicate on the "selected_storage_class" field.
func SelectedStorageClassContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldSelectedStorageClass, v))
}

// TemplateSnapshotIsNil applies the IsNil predicate on the "template_snapshot" field.
func TemplateSnapshotIsNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldIsNull(FieldTemplateSnapshot))
}

// TemplateSnapshotNotNil applies the NotNil predicate on the "template_snapshot" field.
func TemplateSnapshotNotNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldNotNull(FieldTemplateSnapshot))
}

// InstanceSizeSnapshotIsNil applies the IsNil predicate on the "instance_size_snapshot" field.
func InstanceSizeSnapshotIsNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldIsNull(FieldInstanceSizeSnapshot))
}

// InstanceSizeSnapshotNotNil applies the NotNil predicate on the "instance_size_snapshot" field.
func InstanceSizeSnapshotNotNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldNotNull(FieldInstanceSizeSnapshot))
}

// PlacementEvaluationIsNil applies the IsNil predicate on the "placement_evaluation" field.
func PlacementEvaluationIsNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldIsNull(FieldPlacementEvaluation))
}

// PlacementEvaluationNotNil applies the NotNil predicate on the "placement_evaluation" field.
func PlacementEvaluationNotNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldNotNull(FieldPlacementEvaluation))
}

// ModifiedSpecIsNil applies the IsNil predicate on the "modified_spec" field.
func ModifiedSpecIsNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldIsNull(FieldModifiedSpec))
}

// ModifiedSpecNotNil applies the NotNil predicate on the "modified_spec" field.
func ModifiedSpecNotNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldNotNull(FieldModifiedSpec))
}

// ParentTicketIDEQ applies the EQ predicate on the "parent_ticket_id" field.
func ParentTicketIDEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldParentTicketID, v))
}

// ParentTicketIDNEQ applies the NEQ predicate on the "parent_ticket_id" field.
func ParentTicketIDNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldParentTicketID, v))
}

// ParentTicketIDIn applies the In predicate on the "parent_ticket_id" field.
func ParentTicketIDIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldParentTicketID, vs...))
}

// ParentTicketIDNotIn applies the NotIn predicate on the "parent_ticket_id" field.
func ParentTicketIDNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldParentTicketID, vs...))
}

// ParentTicketIDGT applies the GT predicate on the "parent_ticket_id" field.
func ParentTicketIDGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldParentTicketID, v))
}

// ParentTicketIDGTE applies the GTE predicate on the "parent_ticket_id" field.
func ParentTicketIDGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldParentTicketID, v))
}

// ParentTicketIDLT applies the LT predicate on the "parent_ticket_id" field.
func ParentTicketIDLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldParentTicketID, v))
}

// ParentTicketIDLTE applies the LTE predicate on the "parent_ticket_id" field.
func ParentTicketIDLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldParentTicketID, v))
}

// ParentTicketIDContains applies the Contains predicate on the "parent_ticket_id" field.
func ParentTicketIDContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldParentTicketID, v))
}

// ParentTicketIDHasPrefix applies the HasPrefix predicate on the "parent_ticket_id" field.
func ParentTicketIDHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldParentTicketID, v))
}

// ParentTicketIDHasSuffix applies the HasSuffix predicate on the "parent_ticket_id" field.
func ParentTicketIDHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldParentTicketID, v))
}

// ParentTicketIDIsNil applies the IsNil predicate on the "parent_ticket_id" field.
func ParentTicketIDIsNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldIsNull(FieldParentTicketID))
}

// ParentTicketIDNotNil applies the NotNil predicate on the "parent_ticket_id" field.
func ParentTicketIDNotNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldNotNull(FieldParentTicketID))
}

// ParentTicketIDEqualFold applies the EqualFold predicate on the "parent_ticket_id" field.
func ParentTicketIDEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldParentTicketID, v))
}

// ParentTicketIDContainsFold applies the ContainsFold predicate on the "parent_ticket_id" field.
func ParentTicketIDContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldParentTicketID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Ticket) predicate.Ticket {
	return predicate.Ticket(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Ticket) predicate.Ticket {
	return predicate.Ticket(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Ticket) predicate.Ticket {
	return predicate.Ticket(sql.NotPredicates(p))
}
