// Code generated by ent, DO NOT EDIT.

package batchapprovalticket

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the batchapprovalticket type in the database.
	Label = "batch_approval_ticket"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldBatchType holds the string denoting the batch_type field in the database.
	FieldBatchType = "batch_type"
	// FieldChildCount holds the string denoting the child_count field in the database.
	FieldChildCount = "child_count"
	// FieldSuccessCount holds the string denoting the success_count field in the database.
	FieldSuccessCount = "success_count"
	// FieldFailedCount holds the string denoting the failed_count field in the database.
	FieldFailedCount = "failed_count"
	// FieldPendingCount holds the string denoting the pending_count field in the database.
	FieldPendingCount = "pending_count"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// Table holds the table name of the batchapprovalticket in the database.
	Table = "batch_approval_tickets"
)

// Columns holds all SQL columns for batchapprovalticket fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldBatchType,
	FieldChildCount,
	FieldSuccessCount,
	FieldFailedCount,
	FieldPendingCount,
	FieldStatus,
	FieldRequestID,
	FieldCreatedBy,
	FieldReason,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultChildCount holds the default value on creation for the "child_count" field.
	DefaultChildCount int
	// ChildCountValidator is a validator for the "child_count" field. It is called by the builders before save.
	ChildCountValidator func(int) error
	// DefaultSuccessCount holds the default value on creation for the "success_count" field.
	DefaultSuccessCount int
	// SuccessCountValidator is a validator for the "success_count" field. It is called by the builders before save.
	SuccessCountValidator func(int) error
	// DefaultFailedCount holds the default value on creation for the "failed_count" field.
	DefaultFailedCount int
	// FailedCountValidator is a validator for the "failed_count" field. It is called by the builders before save.
	FailedCountValidator func(int) error
	// DefaultPendingCount holds the default value on creation for the "pending_count" field.
	DefaultPendingCount int
	// PendingCountValidator is a validator for the "pending_count" field. It is called by the builders before save.
	PendingCountValidator func(int) error
	// CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	CreatedByValidator func(string) error
)

// BatchType defines the type for the "batch_type" enum field.
type BatchType string

// BatchTypeBATCH_CREATE is the default value of the BatchType enum.
const DefaultBatchType = BatchTypeBATCH_CREATE

// BatchType values.
const (
	BatchTypeBATCH_CREATE  BatchType = "BATCH_CREATE"
	BatchTypeBATCH_DELETE  BatchType = "BATCH_DELETE"
	BatchTypeBATCH_APPROVE BatchType = "BATCH_APPROVE"
	BatchTypeBATCH_POWER   BatchType = "BATCH_POWER"
)

func (bt BatchType) String() string {
	return string(bt)
}

// BatchTypeValidator is a validator for the "batch_type" field enum values. It is called by the builders before save.
func BatchTypeValidator(bt BatchType) error {
	switch bt {
	case BatchTypeBATCH_CREATE, BatchTypeBATCH_DELETE, BatchTypeBATCH_APPROVE, BatchTypeBATCH_POWER:
		return nil
	default:
		return fmt.Errorf("batchapprovalticket: invalid enum value for batch_type field: %q", bt)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusPENDING_APPROVAL is the default value of the Status enum.
const DefaultStatus = StatusPENDING_APPROVAL

// Status values.
const (
	StatusPENDING_APPROVAL Status = "PENDING_APPROVAL"
	StatusIN_PROGRESS      Status = "IN_PROGRESS"
	StatusCOMPLETED        Status = "COMPLETED"
	StatusPARTIAL_SUCCESS  Status = "PARTIAL_SUCCESS"
	StatusFAILED           Status = "FAILED"
	StatusCANCELLED        Status = "CANCELLED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPENDING_APPROVAL, StatusIN_PROGRESS, StatusCOMPLETED, StatusPARTIAL_SUCCESS, StatusFAILED, StatusCANCELLED:
		return nil
	default:
		return fmt.Errorf("batchapprovalticket: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the BatchApprovalTicket queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByBatchType orders the results by the batch_type field.
func ByBatchType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBatchType, opts...).ToFunc()
}

// ByChildCount orders the results by the child_count field.
func ByChildCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChildCount, opts...).ToFunc()
}

// BySuccessCount orders the results by the success_count field.
func BySuccessCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccessCount, opts...).ToFunc()
}

// ByFailedCount orders the results by the failed_count field.
func ByFailedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailedCount, opts...).ToFunc()
}

// ByPendingCount orders the results by the pending_count field.
func ByPendingCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPendingCount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}
