// Code generated by ent, DO NOT EDIT.

package vmrevision

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the vmrevision type in the database.
	Label = "vm_revision"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldRevision holds the string denoting the revision field in the database.
	FieldRevision = "revision"
	// FieldSpec holds the string denoting the spec field in the database.
	FieldSpec = "spec"
	// FieldChangeReason holds the string denoting the change_reason field in the database.
	FieldChangeReason = "change_reason"
	// FieldChangedBy holds the string denoting the changed_by field in the database.
	FieldChangedBy = "changed_by"
	// EdgeVM holds the string denoting the vm edge name in mutations.
	EdgeVM = "vm"
	// Table holds the table name of the vmrevision in the database.
	Table = "vm_revisions"
	// VMTable is the table that holds the vm relation/edge.
	VMTable = "vm_revisions"
	// VMInverseTable is the table name for the VM entity.
	// It exists in this package in order to avoid circular dependency with the "vm" package.
	VMInverseTable = "vms"
	// VMColumn is the table column denoting the vm relation/edge.
	VMColumn = "vm_revisions"
)

// Columns holds all SQL columns for vmrevision fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldRevision,
	FieldSpec,
	FieldChangeReason,
	FieldChangedBy,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "vm_revisions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"vm_revisions",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	RevisionValidator func(int) error
	// ChangedByValidator is a validator for the "changed_by" field. It is called by the builders before save.
	ChangedByValidator func(string) error
)

// OrderOption defines the ordering options for the VMRevision queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByRevision orders the results by the revision field.
func ByRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevision, opts...).ToFunc()
}

// ByChangeReason orders the results by the change_reason field.
func ByChangeReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChangeReason, opts...).ToFunc()
}

// ByChangedBy orders the results by the changed_by field.
func ByChangedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChangedBy, opts...).ToFunc()
}

// ByVMField orders the results by vm field.
func ByVMField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVMStep(), sql.OrderByField(field, opts...))
	}
}
func newVMStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VMInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, VMTable, VMColumn),
	)
}
