// Code generated by ent, DO NOT EDIT.

package vm

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the vm type in the database.
	Label = "vm"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldInstance holds the string denoting the instance field in the database.
	FieldInstance = "instance"
	// FieldNamespace holds the string denoting the namespace field in the database.
	FieldNamespace = "namespace"
	// FieldClusterID holds the string denoting the cluster_id field in the database.
	FieldClusterID = "cluster_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldHostname holds the string denoting the hostname field in the database.
	FieldHostname = "hostname"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldTicketID holds the string denoting the ticket_id field in the database.
	FieldTicketID = "ticket_id"
	// FieldRootVolumeStorageClass holds the string denoting the root_volume_storage_class field in the database.
	FieldRootVolumeStorageClass = "root_volume_storage_class"
	// FieldRootVolumeAccessModes holds the string denoting the root_volume_access_modes field in the database.
	FieldRootVolumeAccessModes = "root_volume_access_modes"
	// FieldRootVolumeVolumeMode holds the string denoting the root_volume_volume_mode field in the database.
	FieldRootVolumeVolumeMode = "root_volume_volume_mode"
	// FieldPollingTier holds the string denoting the polling_tier field in the database.
	FieldPollingTier = "polling_tier"
	// FieldPollIntervalSec holds the string denoting the poll_interval_sec field in the database.
	FieldPollIntervalSec = "poll_interval_sec"
	// FieldLastK8sRv holds the string denoting the last_k8s_rv field in the database.
	FieldLastK8sRv = "last_k8s_rv"
	// FieldLastPolledAt holds the string denoting the last_polled_at field in the database.
	FieldLastPolledAt = "last_polled_at"
	// FieldHighTierSince holds the string denoting the high_tier_since field in the database.
	FieldHighTierSince = "high_tier_since"
	// EdgeService holds the string denoting the service edge name in mutations.
	EdgeService = "service"
	// EdgeRevisions holds the string denoting the revisions edge name in mutations.
	EdgeRevisions = "revisions"
	// Table holds the table name of the vm in the database.
	Table = "vms"
	// ServiceTable is the table that holds the service relation/edge.
	ServiceTable = "vms"
	// ServiceInverseTable is the table name for the Service entity.
	// It exists in this package in order to avoid circular dependency with the "service" package.
	ServiceInverseTable = "services"
	// ServiceColumn is the table column denoting the service relation/edge.
	ServiceColumn = "service_vms"
	// RevisionsTable is the table that holds the revisions relation/edge.
	RevisionsTable = "vm_revisions"
	// RevisionsInverseTable is the table name for the VMRevision entity.
	// It exists in this package in order to avoid circular dependency with the "vmrevision" package.
	RevisionsInverseTable = "vm_revisions"
	// RevisionsColumn is the table column denoting the revisions relation/edge.
	RevisionsColumn = "vm_revisions"
)

// Columns holds all SQL columns for vm fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldInstance,
	FieldNamespace,
	FieldClusterID,
	FieldStatus,
	FieldHostname,
	FieldCreatedBy,
	FieldTicketID,
	FieldRootVolumeStorageClass,
	FieldRootVolumeAccessModes,
	FieldRootVolumeVolumeMode,
	FieldPollingTier,
	FieldPollIntervalSec,
	FieldLastK8sRv,
	FieldLastPolledAt,
	FieldHighTierSince,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "vms"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"service_vms",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// InstanceValidator is a validator for the "instance" field. It is called by the builders before save.
	InstanceValidator func(string) error
	// NamespaceValidator is a validator for the "namespace" field. It is called by the builders before save.
	NamespaceValidator func(string) error
	// CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	CreatedByValidator func(string) error
	// DefaultPollIntervalSec holds the default value on creation for the "poll_interval_sec" field.
	DefaultPollIntervalSec int
)

// Status defines the type for the "status" enum field.
type Status string

// StatusCREATING is the default value of the Status enum.
const DefaultStatus = StatusCREATING

// Status values.
const (
	StatusCREATING  Status = "CREATING"
	StatusSTARTING  Status = "STARTING"
	StatusRUNNING   Status = "RUNNING"
	StatusSTOPPING  Status = "STOPPING"
	StatusSTOPPED   Status = "STOPPED"
	StatusDELETING  Status = "DELETING"
	StatusFAILED    Status = "FAILED"
	StatusPENDING   Status = "PENDING"
	StatusMIGRATING Status = "MIGRATING"
	StatusPAUSED    Status = "PAUSED"
	StatusUNKNOWN   Status = "UNKNOWN"
	StatusNOT_FOUND Status = "NOT_FOUND"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusCREATING, StatusSTARTING, StatusRUNNING, StatusSTOPPING, StatusSTOPPED, StatusDELETING, StatusFAILED, StatusPENDING, StatusMIGRATING, StatusPAUSED, StatusUNKNOWN, StatusNOT_FOUND:
		return nil
	default:
		return fmt.Errorf("vm: invalid enum value for status field: %q", s)
	}
}

// PollingTier defines the type for the "polling_tier" enum field.
type PollingTier string

// PollingTierHigh is the default value of the PollingTier enum.
const DefaultPollingTier = PollingTierHigh

// PollingTier values.
const (
	PollingTierHigh PollingTier = "high"
	PollingTierLow  PollingTier = "low"
)

func (pt PollingTier) String() string {
	return string(pt)
}

// PollingTierValidator is a validator for the "polling_tier" field enum values. It is called by the builders before save.
func PollingTierValidator(pt PollingTier) error {
	switch pt {
	case PollingTierHigh, PollingTierLow:
		return nil
	default:
		return fmt.Errorf("vm: invalid enum value for polling_tier field: %q", pt)
	}
}

// OrderOption defines the ordering options for the VM queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByInstance orders the results by the instance field.
func ByInstance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstance, opts...).ToFunc()
}

// ByNamespace orders the results by the namespace field.
func ByNamespace(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNamespace, opts...).ToFunc()
}

// ByClusterID orders the results by the cluster_id field.
func ByClusterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClusterID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByHostname orders the results by the hostname field.
func ByHostname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHostname, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByTicketID orders the results by the ticket_id field.
func ByTicketID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTicketID, opts...).ToFunc()
}

// ByRootVolumeStorageClass orders the results by the root_volume_storage_class field.
func ByRootVolumeStorageClass(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRootVolumeStorageClass, opts...).ToFunc()
}

// ByRootVolumeVolumeMode orders the results by the root_volume_volume_mode field.
func ByRootVolumeVolumeMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRootVolumeVolumeMode, opts...).ToFunc()
}

// ByPollingTier orders the results by the polling_tier field.
func ByPollingTier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPollingTier, opts...).ToFunc()
}

// ByPollIntervalSec orders the results by the poll_interval_sec field.
func ByPollIntervalSec(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPollIntervalSec, opts...).ToFunc()
}

// ByLastK8sRv orders the results by the last_k8s_rv field.
func ByLastK8sRv(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastK8sRv, opts...).ToFunc()
}

// ByLastPolledAt orders the results by the last_polled_at field.
func ByLastPolledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastPolledAt, opts...).ToFunc()
}

// ByHighTierSince orders the results by the high_tier_since field.
func ByHighTierSince(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHighTierSince, opts...).ToFunc()
}

// ByServiceField orders the results by service field.
func ByServiceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newServiceStep(), sql.OrderByField(field, opts...))
	}
}

// ByRevisionsCount orders the results by revisions count.
func ByRevisionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRevisionsStep(), opts...)
	}
}

// ByRevisions orders the results by revisions terms.
func ByRevisions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRevisionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newServiceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ServiceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ServiceTable, ServiceColumn),
	)
}
func newRevisionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RevisionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RevisionsTable, RevisionsColumn),
	)
}
