// Code generated by ent, DO NOT EDIT.

package vm

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"kv-shepherd.io/shepherd/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.VM {
	return predicate.VM(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.VM {
	return predicate.VM(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldName, v))
}

// Instance applies equality check predicate on the "instance" field. It's identical to InstanceEQ.
func Instance(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldInstance, v))
}

// Namespace applies equality check predicate on the "namespace" field. It's identical to NamespaceEQ.
func Namespace(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldNamespace, v))
}

// ClusterID applies equality check predicate on the "cluster_id" field. It's identical to ClusterIDEQ.
func ClusterID(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldClusterID, v))
}

// Hostname applies equality check predicate on the "hostname" field. It's identical to HostnameEQ.
func Hostname(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldHostname, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldCreatedBy, v))
}

// TicketID applies equality check predicate on the "ticket_id" field. It's identical to TicketIDEQ.
func TicketID(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldTicketID, v))
}

// RootVolumeStorageClass applies equality check predicate on the "root_volume_storage_class" field. It's identical to RootVolumeStorageClassEQ.
func RootVolumeStorageClass(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldRootVolumeStorageClass, v))
}

// RootVolumeVolumeMode applies equality check predicate on the "root_volume_volume_mode" field. It's identical to RootVolumeVolumeModeEQ.
func RootVolumeVolumeMode(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldRootVolumeVolumeMode, v))
}

// PollIntervalSec applies equality check predicate on the "poll_interval_sec" field. It's identical to PollIntervalSecEQ.
func PollIntervalSec(v int) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldPollIntervalSec, v))
}

// LastK8sRv applies equality check predicate on the "last_k8s_rv" field. It's identical to LastK8sRvEQ.
func LastK8sRv(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldLastK8sRv, v))
}

// LastPolledAt applies equality check predicate on the "last_polled_at" field. It's identical to LastPolledAtEQ.
func LastPolledAt(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldLastPolledAt, v))
}

// HighTierSince applies equality check predicate on the "high_tier_since" field. It's identical to HighTierSinceEQ.
func HighTierSince(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldHighTierSince, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.VM {
	return predicate.VM(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.VM {
	return predicate.VM(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.VM {
	return predicate.VM(sql.FieldContainsFold(FieldName, v))
}

// InstanceEQ applies the EQ predicate on the "instance" field.
func InstanceEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldInstance, v))
}

// InstanceNEQ applies the NEQ predicate on the "instance" field.
func InstanceNEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldInstance, v))
}

// InstanceIn applies the In predicate on the "instance" field.
func InstanceIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldInstance, vs...))
}

// InstanceNotIn applies the NotIn predicate on the "instance" field.
func InstanceNotIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldInstance, vs...))
}

// InstanceGT applies the GT predicate on the "instance" field.
func InstanceGT(v string) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldInstance, v))
}

// InstanceGTE applies the GTE predicate on the "instance" field.
func InstanceGTE(v string) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldInstance, v))
}

// InstanceLT applies the LT predicate on the "instance" field.
func InstanceLT(v string) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldInstance, v))
}

// InstanceLTE applies the LTE predicate on the "instance" field.
func InstanceLTE(v string) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldInstance, v))
}

// InstanceContains applies the Contains predicate on the "instance" field.
func InstanceContains(v string) predicate.VM {
	return predicate.VM(sql.FieldContains(FieldInstance, v))
}

// InstanceHasPrefix applies the HasPrefix predicate on the "instance" field.
func InstanceHasPrefix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasPrefix(FieldInstance, v))
}

// InstanceHasSuffix applies the HasSuffix predicate on the "instance" field.
func InstanceHasSuffix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasSuffix(FieldInstance, v))
}

// InstanceEqualFold applies the EqualFold predicate on the "instance" field.
func InstanceEqualFold(v string) predicate.VM {
	return predicate.VM(sql.FieldEqualFold(FieldInstance, v))
}

// InstanceContainsFold applies the ContainsFold predicate on the "instance" field.
func InstanceContainsFold(v string) predicate.VM {
	return predicate.VM(sql.FieldContainsFold(FieldInstance, v))
}

// NamespaceEQ applies the EQ predicate on the "namespace" field.
func NamespaceEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldNamespace, v))
}

// NamespaceNEQ applies the NEQ predicate on the "namespace" field.
func NamespaceNEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldNamespace, v))
}

// NamespaceIn applies the In predicate on the "namespace" field.
func NamespaceIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldNamespace, vs...))
}

// NamespaceNotIn applies the NotIn predicate on the "namespace" field.
func NamespaceNotIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldNamespace, vs...))
}

// NamespaceGT applies the GT predicate on the "namespace" field.
func NamespaceGT(v string) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldNamespace, v))
}

// NamespaceGTE applies the GTE predicate on the "namespace" field.
func NamespaceGTE(v string) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldNamespace, v))
}

// NamespaceLT applies the LT predicate on the "namespace" field.
func NamespaceLT(v string) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldNamespace, v))
}

// NamespaceLTE applies the LTE predicate on the "namespace" field.
func NamespaceLTE(v string) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldNamespace, v))
}

// NamespaceContains applies the Contains predicate on the "namespace" field.
func NamespaceContains(v string) predicate.VM {
	return predicate.VM(sql.FieldContains(FieldNamespace, v))
}

// NamespaceHasPrefix applies the HasPrefix predicate on the "namespace" field.
func NamespaceHasPrefix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasPrefix(FieldNamespace, v))
}

// NamespaceHasSuffix applies the HasSuffix predicate on the "namespace" field.
func NamespaceHasSuffix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasSuffix(FieldNamespace, v))
}

// NamespaceEqualFold applies the EqualFold predicate on the "namespace" field.
func NamespaceEqualFold(v string) predicate.VM {
	return predicate.VM(sql.FieldEqualFold(FieldNamespace, v))
}

// NamespaceContainsFold applies the ContainsFold predicate on the "namespace" field.
func NamespaceContainsFold(v string) predicate.VM {
	return predicate.VM(sql.FieldContainsFold(FieldNamespace, v))
}

// ClusterIDEQ applies the EQ predicate on the "cluster_id" field.
func ClusterIDEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldClusterID, v))
}

// ClusterIDNEQ applies the NEQ predicate on the "cluster_id" field.
func ClusterIDNEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldClusterID, v))
}

// ClusterIDIn applies the In predicate on the "cluster_id" field.
func ClusterIDIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldClusterID, vs...))
}

// ClusterIDNotIn applies the NotIn predicate on the "cluster_id" field.
func ClusterIDNotIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldClusterID, vs...))
}

// ClusterIDGT applies the GT predicate on the "cluster_id" field.
func ClusterIDGT(v string) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldClusterID, v))
}

// ClusterIDGTE applies the GTE predicate on the "cluster_id" field.
func ClusterIDGTE(v string) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldClusterID, v))
}

// ClusterIDLT applies the LT predicate on the "cluster_id" field.
func ClusterIDLT(v string) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldClusterID, v))
}

// ClusterIDLTE applies the LTE predicate on the "cluster_id" field.
func ClusterIDLTE(v string) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldClusterID, v))
}

// ClusterIDContains applies the Contains predicate on the "cluster_id" field.
func ClusterIDContains(v string) predicate.VM {
	return predicate.VM(sql.FieldContains(FieldClusterID, v))
}

// ClusterIDHasPrefix applies the HasPrefix predicate on the "cluster_id" field.
func ClusterIDHasPrefix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasPrefix(FieldClusterID, v))
}

// ClusterIDHasSuffix applies the HasSuffix predicate on the "cluster_id" field.
func ClusterIDHasSuffix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasSuffix(FieldClusterID, v))
}

// ClusterIDIsNil applies the IsNil predicate on the "cluster_id" field.
func ClusterIDIsNil() predicate.VM {
	return predicate.VM(sql.FieldIsNull(FieldClusterID))
}

// ClusterIDNotNil applies the NotNil predicate on the "cluster_id" field.
func ClusterIDNotNil() predicate.VM {
	return predicate.VM(sql.FieldNotNull(FieldClusterID))
}

// ClusterIDEqualFold applies the EqualFold predicate on the "cluster_id" field.
func ClusterIDEqualFold(v string) predicate.VM {
	return predicate.VM(sql.FieldEqualFold(FieldClusterID, v))
}

// ClusterIDContainsFold applies the ContainsFold predicate on the "cluster_id" field.
func ClusterIDContainsFold(v string) predicate.VM {
	return predicate.VM(sql.FieldContainsFold(FieldClusterID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldStatus, vs...))
}

// HostnameEQ applies the EQ predicate on the "hostname" field.
func HostnameEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldHostname, v))
}

// HostnameNEQ applies the NEQ predicate on the "hostname" field.
func HostnameNEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldHostname, v))
}

// HostnameIn applies the In predicate on the "hostname" field.
func HostnameIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldHostname, vs...))
}

// HostnameNotIn applies the NotIn predicate on the "hostname" field.
func HostnameNotIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldHostname, vs...))
}

// HostnameGT applies the GT predicate on the "hostname" field.
func HostnameGT(v string) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldHostname, v))
}

// HostnameGTE applies the GTE predicate on the "hostname" field.
func HostnameGTE(v string) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldHostname, v))
}

// HostnameLT applies the LT predicate on the "hostname" field.
func HostnameLT(v string) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldHostname, v))
}

// HostnameLTE applies the LTE predicate on the "hostname" field.
func HostnameLTE(v string) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldHostname, v))
}

// HostnameContains applies the Contains predicate on the "hostname" field.
func HostnameContains(v string) predicate.VM {
	return predicate.VM(sql.FieldContains(FieldHostname, v))
}

// HostnameHasPrefix applies the HasPrefix predicate on the "hostname" field.
func HostnameHasPrefix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasPrefix(FieldHostname, v))
}

// HostnameHasSuffix applies the HasSuffix predicate on the "hostname" field.
func HostnameHasSuffix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasSuffix(FieldHostname, v))
}

// HostnameIsNil applies the IsNil predicate on the "hostname" field.
func HostnameIsNil() predicate.VM {
	return predicate.VM(sql.FieldIsNull(FieldHostname))
}

// HostnameNotNil applies the NotNil predicate on the "hostname" field.
func HostnameNotNil() predicate.VM {
	return predicate.VM(sql.FieldNotNull(FieldHostname))
}

// HostnameEqualFold applies the EqualFold predicate on the "hostname" field.
func HostnameEqualFold(v string) predicate.VM {
	return predicate.VM(sql.FieldEqualFold(FieldHostname, v))
}

// HostnameContainsFold applies the ContainsFold predicate on the "hostname" field.
func HostnameContainsFold(v string) predicate.VM {
	return predicate.VM(sql.FieldContainsFold(FieldHostname, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.VM {
	return predicate.VM(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.VM {
	return predicate.VM(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.VM {
	return predicate.VM(sql.FieldContainsFold(FieldCreatedBy, v))
}

// TicketIDEQ applies the EQ predicate on the "ticket_id" field.
func TicketIDEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldTicketID, v))
}

// TicketIDNEQ applies the NEQ predicate on the "ticket_id" field.
func TicketIDNEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldTicketID, v))
}

// TicketIDIn applies the In predicate on the "ticket_id" field.
func TicketIDIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldTicketID, vs...))
}

// TicketIDNotIn applies the NotIn predicate on the "ticket_id" field.
func TicketIDNotIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldTicketID, vs...))
}

// TicketIDGT applies the GT predicate on the "ticket_id" field.
func TicketIDGT(v string) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldTicketID, v))
}

// TicketIDGTE applies the GTE predicate on the "ticket_id" field.
func TicketIDGTE(v string) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldTicketID, v))
}

// TicketIDLT applies the LT predicate on the "ticket_id" field.
func TicketIDLT(v string) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldTicketID, v))
}

// TicketIDLTE applies the LTE predicate on the "ticket_id" field.
func TicketIDLTE(v string) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldTicketID, v))
}

// TicketIDContains applies the Contains predicate on the "ticket_id" field.
func TicketIDContains(v string) predicate.VM {
	return predicate.VM(sql.FieldContains(FieldTicketID, v))
}

// TicketIDHasPrefix applies the HasPrefix predicate on the "ticket_id" field.
func TicketIDHasPrefix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasPrefix(FieldTicketID, v))
}

// TicketIDHasSuffix applies the HasSuffix predicate on the "ticket_id" field.
func TicketIDHasSuffix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasSuffix(FieldTicketID, v))
}

// TicketIDIsNil applies the IsNil predicate on the "ticket_id" field.
func TicketIDIsNil() predicate.VM {
	return predicate.VM(sql.FieldIsNull(FieldTicketID))
}

// TicketIDNotNil applies the NotNil predicate on the "ticket_id" field.
func TicketIDNotNil() predicate.VM {
	return predicate.VM(sql.FieldNotNull(FieldTicketID))
}

// TicketIDEqualFold applies the EqualFold predicate on the "ticket_id" field.
func TicketIDEqualFold(v string) predicate.VM {
	return predicate.VM(sql.FieldEqualFold(FieldTicketID, v))
}

// TicketIDContainsFold applies the ContainsFold predicate on the "ticket_id" field.
func TicketIDContainsFold(v string) predicate.VM {
	return predicate.VM(sql.FieldContainsFold(FieldTicketID, v))
}

// RootVolumeStorageClassEQ applies the EQ predicate on the "root_volume_storage_class" field.
func RootVolumeStorageClassEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldRootVolumeStorageClass, v))
}

// RootVolumeStorageClassNEQ applies the NEQ predicate on the "root_volume_storage_class" field.
func RootVolumeStorageClassNEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldRootVolumeStorageClass, v))
}

// RootVolumeStorageClassIn applies the In predicate on the "root_volume_storage_class" field.
func RootVolumeStorageClassIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldRootVolumeStorageClass, vs...))
}

// RootVolumeStorageClassNotIn applies the NotIn predicate on the "root_volume_storage_class" field.
func RootVolumeStorageClassNotIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldRootVolumeStorageClass, vs...))
}

// RootVolumeStorageClassGT applies the GT predicate on the "root_volume_storage_class" field.
func RootVolumeStorageClassGT(v string) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldRootVolumeStorageClass, v))
}

// RootVolumeStorageClassGTE applies the GTE predicate on the "root_volume_storage_class" field.
func RootVolumeStorageClassGTE(v string) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldRootVolumeStorageClass, v))
}

// RootVolumeStorageClassLT applies the LT predicate on the "root_volume_storage_class" field.
func RootVolumeStorageClassLT(v string) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldRootVolumeStorageClass, v))
}

// RootVolumeStorageClassLTE applies the LTE predicate on the "root_volume_storage_class" field.
func RootVolumeStorageClassLTE(v string) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldRootVolumeStorageClass, v))
}

// RootVolumeStorageClassContains applies the Contains predicate on the "root_volume_storage_class" field.
func RootVolumeStorageClassContains(v string) predicate.VM {
	return predicate.VM(sql.FieldContains(FieldRootVolumeStorageClass, v))
}

// RootVolumeStorageClassHasPrefix applies the HasPrefix predicate on the "root_volume_storage_class" field.
func RootVolumeStorageClassHasPrefix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasPrefix(FieldRootVolumeStorageClass, v))
}

// RootVolumeStorageClassHasSuffix applies the HasSuffix predicate on the "root_volume_storage_class" field.
func RootVolumeStorageClassHasSuffix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasSuffix(FieldRootVolumeStorageClass, v))
}

// RootVolumeStorageClassIsNil applies the IsNil predicate on the "root_volume_storage_class" field.
func RootVolumeStorageClassIsNil() predicate.VM {
	return predicate.VM(sql.FieldIsNull(FieldRootVolumeStorageClass))
}

// RootVolumeStorageClassNotNil applies the NotNil predicate on the "root_volume_storage_class" field.
func RootVolumeStorageClassNotNil() predicate.VM {
	return predicate.VM(sql.FieldNotNull(FieldRootVolumeStorageClass))
}

// RootVolumeStorageClassEqualFold applies the EqualFold predicate on the "root_volume_storage_class" field.
func RootVolumeStorageClassEqualFold(v string) predicate.VM {
	return predicate.VM(sql.FieldEqualFold(FieldRootVolumeStorageClass, v))
}

// RootVolumeStorageClassContainsFold applies the ContainsFold predicate on the "root_volume_storage_class" field.
func RootVolumeStorageClassContainsFold(v string) predicate.VM {
	return predicate.VM(sql.FieldContainsFold(FieldRootVolumeStorageClass, v))
}

// RootVolumeAccessModesIsNil applies the IsNil predicate on the "root_volume_access_modes" field.
func RootVolumeAccessModesIsNil() predicate.VM {
	return predicate.VM(sql.FieldIsNull(FieldRootVolumeAccessModes))
}

// RootVolumeAccessModesNotNil applies the NotNil predicate on the "root_volume_access_modes" field.
func RootVolumeAccessModesNotNil() predicate.VM {
	return predicate.VM(sql.FieldNotNull(FieldRootVolumeAccessModes))
}

// RootVolumeVolumeModeEQ applies the EQ predicate on the "root_volume_volume_mode" field.
func RootVolumeVolumeModeEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldRootVolumeVolumeMode, v))
}

// RootVolumeVolumeModeNEQ applies the NEQ predicate on the "root_volume_volume_mode" field.
func RootVolumeVolumeModeNEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldRootVolumeVolumeMode, v))
}

// RootVolumeVolumeModeIn applies the In predicate on the "root_volume_volume_mode" field.
func RootVolumeVolumeModeIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldRootVolumeVolumeMode, vs...))
}

// RootVolumeVolumeModeNotIn applies the NotIn predicate on the "root_volume_volume_mode" field.
func RootVolumeVolumeModeNotIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldRootVolumeVolumeMode, vs...))
}

// RootVolumeVolumeModeGT applies the GT predicate on the "root_volume_volume_mode" field.
func RootVolumeVolumeModeGT(v string) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldRootVolumeVolumeMode, v))
}

// RootVolumeVolumeModeGTE applies the GTE predicate on the "root_volume_volume_mode" field.
func RootVolumeVolumeModeGTE(v string) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldRootVolumeVolumeMode, v))
}

// RootVolumeVolumeModeLT applies the LT predicate on the "root_volume_volume_mode" field.
func RootVolumeVolumeModeLT(v string) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldRootVolumeVolumeMode, v))
}

// RootVolumeVolumeModeLTE applies the LTE predicate on the "root_volume_volume_mode" field.
func RootVolumeVolumeModeLTE(v string) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldRootVolumeVolumeMode, v))
}

// RootVolumeVolumeModeContains applies the Contains predicate on the "root_volume_volume_mode" field.
func RootVolumeVolumeModeContains(v string) predicate.VM {
	return predicate.VM(sql.FieldContains(FieldRootVolumeVolumeMode, v))
}

// RootVolumeVolumeModeHasPrefix applies the HasPrefix predicate on the "root_volume_volume_mode" field.
func RootVolumeVolumeModeHasPrefix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasPrefix(FieldRootVolumeVolumeMode, v))
}

// RootVolumeVolumeModeHasSuffix applies the HasSuffix predicate on the "root_volume_volume_mode" field.
func RootVolumeVolumeModeHasSuffix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasSuffix(FieldRootVolumeVolumeMode, v))
}

// RootVolumeVolumeModeIsNil applies the IsNil predicate on the "root_volume_volume_mode" field.
func RootVolumeVolumeModeIsNil() predicate.VM {
	return predicate.VM(sql.FieldIsNull(FieldRootVolumeVolumeMode))
}

// RootVolumeVolumeModeNotNil applies the NotNil predicate on the "root_volume_volume_mode" field.
func RootVolumeVolumeModeNotNil() predicate.VM {
	return predicate.VM(sql.FieldNotNull(FieldRootVolumeVolumeMode))
}

// RootVolumeVolumeModeEqualFold applies the EqualFold predicate on the "root_volume_volume_mode" field.
func RootVolumeVolumeModeEqualFold(v string) predicate.VM {
	return predicate.VM(sql.FieldEqualFold(FieldRootVolumeVolumeMode, v))
}

// RootVolumeVolumeModeContainsFold applies the ContainsFold predicate on the "root_volume_volume_mode" field.
func RootVolumeVolumeModeContainsFold(v string) predicate.VM {
	return predicate.VM(sql.FieldContainsFold(FieldRootVolumeVolumeMode, v))
}

// PollingTierEQ applies the EQ predicate on the "polling_tier" field.
func PollingTierEQ(v PollingTier) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldPollingTier, v))
}

// PollingTierNEQ applies the NEQ predicate on the "polling_tier" field.
func PollingTierNEQ(v PollingTier) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldPollingTier, v))
}

// PollingTierIn applies the In predicate on the "polling_tier" field.
func PollingTierIn(vs ...PollingTier) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldPollingTier, vs...))
}

// PollingTierNotIn applies the NotIn predicate on the "polling_tier" field.
func PollingTierNotIn(vs ...PollingTier) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldPollingTier, vs...))
}

// PollIntervalSecEQ applies the EQ predicate on the "poll_interval_sec" field.
func PollIntervalSecEQ(v int) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldPollIntervalSec, v))
}

// PollIntervalSecNEQ applies the NEQ predicate on the "poll_interval_sec" field.
func PollIntervalSecNEQ(v int) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldPollIntervalSec, v))
}

// PollIntervalSecIn applies the In predicate on the "poll_interval_sec" field.
func PollIntervalSecIn(vs ...int) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldPollIntervalSec, vs...))
}

// PollIntervalSecNotIn applies the NotIn predicate on the "poll_interval_sec" field.
func PollIntervalSecNotIn(vs ...int) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldPollIntervalSec, vs...))
}

// PollIntervalSecGT applies the GT predicate on the "poll_interval_sec" field.
func PollIntervalSecGT(v int) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldPollIntervalSec, v))
}

// PollIntervalSecGTE applies the GTE predicate on the "poll_interval_sec" field.
func PollIntervalSecGTE(v int) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldPollIntervalSec, v))
}

// PollIntervalSecLT applies the LT predicate on the "poll_interval_sec" field.
func PollIntervalSecLT(v int) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldPollIntervalSec, v))
}

// PollIntervalSecLTE applies the LTE predicate on the "poll_interval_sec" field.
func PollIntervalSecLTE(v int) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldPollIntervalSec, v))
}

// LastK8sRvEQ applies the EQ predicate on the "last_k8s_rv" field.
func LastK8sRvEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldLastK8sRv, v))
}

// LastK8sRvNEQ applies the NEQ predicate on the "last_k8s_rv" field.
func LastK8sRvNEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldLastK8sRv, v))
}

// LastK8sRvIn applies the In predicate on the "last_k8s_rv" field.
func LastK8sRvIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldLastK8sRv, vs...))
}

// LastK8sRvNotIn applies the NotIn predicate on the "last_k8s_rv" field.
func LastK8sRvNotIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldLastK8sRv, vs...))
}

// LastK8sRvGT applies the GT predicate on the "last_k8s_rv" field.
func LastK8sRvGT(v string) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldLastK8sRv, v))
}

// LastK8sRvGTE applies the GTE predicate on the "last_k8s_rv" field.
func LastK8sRvGTE(v string) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldLastK8sRv, v))
}

// LastK8sRvLT applies the LT predicate on the "last_k8s_rv" field.
func LastK8sRvLT(v string) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldLastK8sRv, v))
}

// LastK8sRvLTE applies the LTE predicate on the "last_k8s_rv" field.
func LastK8sRvLTE(v string) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldLastK8sRv, v))
}

// LastK8sRvContains applies the Contains predicate on the "last_k8s_rv" field.
func LastK8sRvContains(v string) predicate.VM {
	return predicate.VM(sql.FieldContains(FieldLastK8sRv, v))
}

// LastK8sRvHasPrefix applies the HasPrefix predicate on the "last_k8s_rv" field.
func LastK8sRvHasPrefix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasPrefix(FieldLastK8sRv, v))
}

// LastK8sRvHasSuffix applies the HasSuffix predicate on the "last_k8s_rv" field.
func LastK8sRvHasSuffix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasSuffix(FieldLastK8sRv, v))
}

// LastK8sRvIsNil applies the IsNil predicate on the "last_k8s_rv" field.
func LastK8sRvIsNil() predicate.VM {
	return predicate.VM(sql.FieldIsNull(FieldLastK8sRv))
}

// LastK8sRvNotNil applies the NotNil predicate on the "last_k8s_rv" field.
func LastK8sRvNotNil() predicate.VM {
	return predicate.VM(sql.FieldNotNull(FieldLastK8sRv))
}

// LastK8sRvEqualFold applies the EqualFold predicate on the "last_k8s_rv" field.
func LastK8sRvEqualFold(v string) predicate.VM {
	return predicate.VM(sql.FieldEqualFold(FieldLastK8sRv, v))
}

// LastK8sRvContainsFold applies the ContainsFold predicate on the "last_k8s_rv" field.
func LastK8sRvContainsFold(v string) predicate.VM {
	return predicate.VM(sql.FieldContainsFold(FieldLastK8sRv, v))
}

// LastPolledAtEQ applies the EQ predicate on the "last_polled_at" field.
func LastPolledAtEQ(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldLastPolledAt, v))
}

// LastPolledAtNEQ applies the NEQ predicate on the "last_polled_at" field.
func LastPolledAtNEQ(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldLastPolledAt, v))
}

// LastPolledAtIn applies the In predicate on the "last_polled_at" field.
func LastPolledAtIn(vs ...time.Time) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldLastPolledAt, vs...))
}

// LastPolledAtNotIn applies the NotIn predicate on the "last_polled_at" field.
func LastPolledAtNotIn(vs ...time.Time) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldLastPolledAt, vs...))
}

// LastPolledAtGT applies the GT predicate on the "last_polled_at" field.
func LastPolledAtGT(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldLastPolledAt, v))
}

// LastPolledAtGTE applies the GTE predicate on the "last_polled_at" field.
func LastPolledAtGTE(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldLastPolledAt, v))
}

// LastPolledAtLT applies the LT predicate on the "last_polled_at" field.
func LastPolledAtLT(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldLastPolledAt, v))
}

// LastPolledAtLTE applies the LTE predicate on the "last_polled_at" field.
func LastPolledAtLTE(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldLastPolledAt, v))
}

// LastPolledAtIsNil applies the IsNil predicate on the "last_polled_at" field.
func LastPolledAtIsNil() predicate.VM {
	return predicate.VM(sql.FieldIsNull(FieldLastPolledAt))
}

// LastPolledAtNotNil applies the NotNil predicate on the "last_polled_at" field.
func LastPolledAtNotNil() predicate.VM {
	return predicate.VM(sql.FieldNotNull(FieldLastPolledAt))
}

// HighTierSinceEQ applies the EQ predicate on the "high_tier_since" field.
func HighTierSinceEQ(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldHighTierSince, v))
}

// HighTierSinceNEQ applies the NEQ predicate on the "high_tier_since" field.
func HighTierSinceNEQ(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldHighTierSince, v))
}

// HighTierSinceIn applies the In predicate on the "high_tier_since" field.
func HighTierSinceIn(vs ...time.Time) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldHighTierSince, vs...))
}

// HighTierSinceNotIn applies the NotIn predicate on the "high_tier_since" field.
func HighTierSinceNotIn(vs ...time.Time) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldHighTierSince, vs...))
}

// HighTierSinceGT applies the GT predicate on the "high_tier_since" field.
func HighTierSinceGT(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldHighTierSince, v))
}

// HighTierSinceGTE applies the GTE predicate on the "high_tier_since" field.
func HighTierSinceGTE(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldHighTierSince, v))
}

// HighTierSinceLT applies the LT predicate on the "high_tier_since" field.
func HighTierSinceLT(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldHighTierSince, v))
}

// HighTierSinceLTE applies the LTE predicate on the "high_tier_since" field.
func HighTierSinceLTE(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldHighTierSince, v))
}

// HighTierSinceIsNil applies the IsNil predicate on the "high_tier_since" field.
func HighTierSinceIsNil() predicate.VM {
	return predicate.VM(sql.FieldIsNull(FieldHighTierSince))
}

// HighTierSinceNotNil applies the NotNil predicate on the "high_tier_since" field.
func HighTierSinceNotNil() predicate.VM {
	return predicate.VM(sql.FieldNotNull(FieldHighTierSince))
}

// HasService applies the HasEdge predicate on the "service" edge.
func HasService() predicate.VM {
	return predicate.VM(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ServiceTable, ServiceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasServiceWith applies the HasEdge predicate on the "service" edge with a given conditions (other predicates).
func HasServiceWith(preds ...predicate.Service) predicate.VM {
	return predicate.VM(func(s *sql.Selector) {
		step := newServiceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRevisions applies the HasEdge predicate on the "revisions" edge.
func HasRevisions() predicate.VM {
	return predicate.VM(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RevisionsTable, RevisionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRevisionsWith applies the HasEdge predicate on the "revisions" edge with a given conditions (other predicates).
func HasRevisionsWith(preds ...predicate.VMRevision) predicate.VM {
	return predicate.VM(func(s *sql.Selector) {
		step := newRevisionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VM) predicate.VM {
	return predicate.VM(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VM) predicate.VM {
	return predicate.VM(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VM) predicate.VM {
	return predicate.VM(sql.NotPredicates(p))
}
