// Code generated by ent, DO NOT EDIT.

package pendingadoption

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"kv-shepherd.io/shepherd/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEQ(FieldUpdatedAt, v))
}

// ClusterID applies equality check predicate on the "cluster_id" field. It's identical to ClusterIDEQ.
func ClusterID(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEQ(FieldClusterID, v))
}

// Namespace applies equality check predicate on the "namespace" field. It's identical to NamespaceEQ.
func Namespace(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEQ(FieldNamespace, v))
}

// ResourceName applies equality check predicate on the "resource_name" field. It's identical to ResourceNameEQ.
func ResourceName(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEQ(FieldResourceName, v))
}

// ResourceType applies equality check predicate on the "resource_type" field. It's identical to ResourceTypeEQ.
func ResourceType(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEQ(FieldResourceType, v))
}

// DiscoveredBy applies equality check predicate on the "discovered_by" field. It's identical to DiscoveredByEQ.
func DiscoveredBy(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEQ(FieldDiscoveredBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldLTE(FieldUpdatedAt, v))
}

// ClusterIDEQ applies the EQ predicate on the "cluster_id" field.
func ClusterIDEQ(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEQ(FieldClusterID, v))
}

// ClusterIDNEQ applies the NEQ predicate on the "cluster_id" field.
func ClusterIDNEQ(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldNEQ(FieldClusterID, v))
}

// ClusterIDIn applies the In predicate on the "cluster_id" field.
func ClusterIDIn(vs ...string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldIn(FieldClusterID, vs...))
}

// ClusterIDNotIn applies the NotIn predicate on the "cluster_id" field.
func ClusterIDNotIn(vs ...string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldNotIn(FieldClusterID, vs...))
}

// ClusterIDGT applies the GT predicate on the "cluster_id" field.
func ClusterIDGT(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldGT(FieldClusterID, v))
}

// ClusterIDGTE applies the GTE predicate on the "cluster_id" field.
func ClusterIDGTE(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldGTE(FieldClusterID, v))
}

// ClusterIDLT applies the LT predicate on the "cluster_id" field.
func ClusterIDLT(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldLT(FieldClusterID, v))
}

// ClusterIDLTE applies the LTE predicate on the "cluster_id" field.
func ClusterIDLTE(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldLTE(FieldClusterID, v))
}

// ClusterIDContains applies the Contains predicate on the "cluster_id" field.
func ClusterIDContains(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldContains(FieldClusterID, v))
}

// ClusterIDHasPrefix applies the HasPrefix predicate on the "cluster_id" field.
func ClusterIDHasPrefix(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldHasPrefix(FieldClusterID, v))
}

// ClusterIDHasSuffix applies the HasSuffix predicate on the "cluster_id" field.
func ClusterIDHasSuffix(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldHasSuffix(FieldClusterID, v))
}

// ClusterIDEqualFold applies the EqualFold predicate on the "cluster_id" field.
func ClusterIDEqualFold(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEqualFold(FieldClusterID, v))
}

// ClusterIDContainsFold applies the ContainsFold predicate on the "cluster_id" field.
func ClusterIDContainsFold(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldContainsFold(FieldClusterID, v))
}

// NamespaceEQ applies the EQ predicate on the "namespace" field.
func NamespaceEQ(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEQ(FieldNamespace, v))
}

// NamespaceNEQ applies the NEQ predicate on the "namespace" field.
func NamespaceNEQ(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldNEQ(FieldNamespace, v))
}

// NamespaceIn applies the In predicate on the "namespace" field.
func NamespaceIn(vs ...string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldIn(FieldNamespace, vs...))
}

// NamespaceNotIn applies the NotIn predicate on the "namespace" field.
func NamespaceNotIn(vs ...string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldNotIn(FieldNamespace, vs...))
}

// NamespaceGT applies the GT predicate on the "namespace" field.
func NamespaceGT(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldGT(FieldNamespace, v))
}

// NamespaceGTE applies the GTE predicate on the "namespace" field.
func NamespaceGTE(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldGTE(FieldNamespace, v))
}

// NamespaceLT applies the LT predicate on the "namespace" field.
func NamespaceLT(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldLT(FieldNamespace, v))
}

// NamespaceLTE applies the LTE predicate on the "namespace" field.
func NamespaceLTE(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldLTE(FieldNamespace, v))
}

// NamespaceContains applies the Contains predicate on the "namespace" field.
func NamespaceContains(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldContains(FieldNamespace, v))
}

// NamespaceHasPrefix applies the HasPrefix predicate on the "namespace" field.
func NamespaceHasPrefix(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldHasPrefix(FieldNamespace, v))
}

// NamespaceHasSuffix applies the HasSuffix predicate on the "namespace" field.
func NamespaceHasSuffix(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldHasSuffix(FieldNamespace, v))
}

// NamespaceEqualFold applies the EqualFold predicate on the "namespace" field.
func NamespaceEqualFold(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEqualFold(FieldNamespace, v))
}

// NamespaceContainsFold applies the ContainsFold predicate on the "namespace" field.
func NamespaceContainsFold(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldContainsFold(FieldNamespace, v))
}

// ResourceNameEQ applies the EQ predicate on the "resource_name" field.
func ResourceNameEQ(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEQ(FieldResourceName, v))
}

// ResourceNameNEQ applies the NEQ predicate on the "resource_name" field.
func ResourceNameNEQ(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldNEQ(FieldResourceName, v))
}

// ResourceNameIn applies the In predicate on the "resource_name" field.
func ResourceNameIn(vs ...string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldIn(FieldResourceName, vs...))
}

// ResourceNameNotIn applies the NotIn predicate on the "resource_name" field.
func ResourceNameNotIn(vs ...string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldNotIn(FieldResourceName, vs...))
}

// ResourceNameGT applies the GT predicate on the "resource_name" field.
func ResourceNameGT(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldGT(FieldResourceName, v))
}

// ResourceNameGTE applies the GTE predicate on the "resource_name" field.
func ResourceNameGTE(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldGTE(FieldResourceName, v))
}

// ResourceNameLT applies the LT predicate on the "resource_name" field.
func ResourceNameLT(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldLT(FieldResourceName, v))
}

// ResourceNameLTE applies the LTE predicate on the "resource_name" field.
func ResourceNameLTE(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldLTE(FieldResourceName, v))
}

// ResourceNameContains applies the Contains predicate on the "resource_name" field.
func ResourceNameContains(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldContains(FieldResourceName, v))
}

// ResourceNameHasPrefix applies the HasPrefix predicate on the "resource_name" field.
func ResourceNameHasPrefix(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldHasPrefix(FieldResourceName, v))
}

// ResourceNameHasSuffix applies the HasSuffix predicate on the "resource_name" field.
func ResourceNameHasSuffix(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldHasSuffix(FieldResourceName, v))
}

// ResourceNameEqualFold applies the EqualFold predicate on the "resource_name" field.
func ResourceNameEqualFold(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEqualFold(FieldResourceName, v))
}

// ResourceNameContainsFold applies the ContainsFold predicate on the "resource_name" field.
func ResourceNameContainsFold(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldContainsFold(FieldResourceName, v))
}

// ResourceTypeEQ applies the EQ predicate on the "resource_type" field.
func ResourceTypeEQ(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEQ(FieldResourceType, v))
}

// ResourceTypeNEQ applies the NEQ predicate on the "resource_type" field.
func ResourceTypeNEQ(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldNEQ(FieldResourceType, v))
}

// ResourceTypeIn applies the In predicate on the "resource_type" field.
func ResourceTypeIn(vs ...string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldIn(FieldResourceType, vs...))
}

// ResourceTypeNotIn applies the NotIn predicate on the "resource_type" field.
func ResourceTypeNotIn(vs ...string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldNotIn(FieldResourceType, vs...))
}

// ResourceTypeGT applies the GT predicate on the "resource_type" field.
func ResourceTypeGT(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldGT(FieldResourceType, v))
}

// ResourceTypeGTE applies the GTE predicate on the "resource_type" field.
func ResourceTypeGTE(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldGTE(FieldResourceType, v))
}

// ResourceTypeLT applies the LT predicate on the "resource_type" field.
func ResourceTypeLT(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldLT(FieldResourceType, v))
}

// ResourceTypeLTE applies the LTE predicate on the "resource_type" field.
func ResourceTypeLTE(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldLTE(FieldResourceType, v))
}

// ResourceTypeContains applies the Contains predicate on the "resource_type" field.
func ResourceTypeContains(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldContains(FieldResourceType, v))
}

// ResourceTypeHasPrefix applies the HasPrefix predicate on the "resource_type" field.
func ResourceTypeHasPrefix(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldHasPrefix(FieldResourceType, v))
}

// ResourceTypeHasSuffix applies the HasSuffix predicate on the "resource_type" field.
func ResourceTypeHasSuffix(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldHasSuffix(FieldResourceType, v))
}

// ResourceTypeEqualFold applies the EqualFold predicate on the "resource_type" field.
func ResourceTypeEqualFold(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEqualFold(FieldResourceType, v))
}

// ResourceTypeContainsFold applies the ContainsFold predicate on the "resource_type" field.
func ResourceTypeContainsFold(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldContainsFold(FieldResourceType, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldNotIn(FieldStatus, vs...))
}

// DiscoveredByEQ applies the EQ predicate on the "discovered_by" field.
func DiscoveredByEQ(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEQ(FieldDiscoveredBy, v))
}

// DiscoveredByNEQ applies the NEQ predicate on the "discovered_by" field.
func DiscoveredByNEQ(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldNEQ(FieldDiscoveredBy, v))
}

// DiscoveredByIn applies the In predicate on the "discovered_by" field.
func DiscoveredByIn(vs ...string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldIn(FieldDiscoveredBy, vs...))
}

// DiscoveredByNotIn applies the NotIn predicate on the "discovered_by" field.
func DiscoveredByNotIn(vs ...string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldNotIn(FieldDiscoveredBy, vs...))
}

// DiscoveredByGT applies the GT predicate on the "discovered_by" field.
func DiscoveredByGT(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldGT(FieldDiscoveredBy, v))
}

// DiscoveredByGTE applies the GTE predicate on the "discovered_by" field.
func DiscoveredByGTE(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldGTE(FieldDiscoveredBy, v))
}

// DiscoveredByLT applies the LT predicate on the "discovered_by" field.
func DiscoveredByLT(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldLT(FieldDiscoveredBy, v))
}

// DiscoveredByLTE applies the LTE predicate on the "discovered_by" field.
func DiscoveredByLTE(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldLTE(FieldDiscoveredBy, v))
}

// DiscoveredByContains applies the Contains predicate on the "discovered_by" field.
func DiscoveredByContains(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldContains(FieldDiscoveredBy, v))
}

// DiscoveredByHasPrefix applies the HasPrefix predicate on the "discovered_by" field.
func DiscoveredByHasPrefix(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldHasPrefix(FieldDiscoveredBy, v))
}

// DiscoveredByHasSuffix applies the HasSuffix predicate on the "discovered_by" field.
func DiscoveredByHasSuffix(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldHasSuffix(FieldDiscoveredBy, v))
}

// DiscoveredByIsNil applies the IsNil predicate on the "discovered_by" field.
func DiscoveredByIsNil() predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldIsNull(FieldDiscoveredBy))
}

// DiscoveredByNotNil applies the NotNil predicate on the "discovered_by" field.
func DiscoveredByNotNil() predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldNotNull(FieldDiscoveredBy))
}

// DiscoveredByEqualFold applies the EqualFold predicate on the "discovered_by" field.
func DiscoveredByEqualFold(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldEqualFold(FieldDiscoveredBy, v))
}

// DiscoveredByContainsFold applies the ContainsFold predicate on the "discovered_by" field.
func DiscoveredByContainsFold(v string) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldContainsFold(FieldDiscoveredBy, v))
}

// LabelsIsNil applies the IsNil predicate on the "labels" field.
func LabelsIsNil() predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldIsNull(FieldLabels))
}

// LabelsNotNil applies the NotNil predicate on the "labels" field.
func LabelsNotNil() predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.FieldNotNull(FieldLabels))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PendingAdoption) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PendingAdoption) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PendingAdoption) predicate.PendingAdoption {
	return predicate.PendingAdoption(sql.NotPredicates(p))
}
