// Code generated by ent, DO NOT EDIT.

package ratelimituseroverride

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"kv-shepherd.io/shepherd/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldEQ(FieldUpdatedAt, v))
}

// MaxPendingParents applies equality check predicate on the "max_pending_parents" field. It's identical to MaxPendingParentsEQ.
func MaxPendingParents(v int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldEQ(FieldMaxPendingParents, v))
}

// MaxPendingChildren applies equality check predicate on the "max_pending_children" field. It's identical to MaxPendingChildrenEQ.
func MaxPendingChildren(v int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldEQ(FieldMaxPendingChildren, v))
}

// CooldownSeconds applies equality check predicate on the "cooldown_seconds" field. It's identical to CooldownSecondsEQ.
func CooldownSeconds(v int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldEQ(FieldCooldownSeconds, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldEQ(FieldReason, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldEQ(FieldUpdatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldLTE(FieldUpdatedAt, v))
}

// MaxPendingParentsEQ applies the EQ predicate on the "max_pending_parents" field.
func MaxPendingParentsEQ(v int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldEQ(FieldMaxPendingParents, v))
}

// MaxPendingParentsNEQ applies the NEQ predicate on the "max_pending_parents" field.
func MaxPendingParentsNEQ(v int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldNEQ(FieldMaxPendingParents, v))
}

// MaxPendingParentsIn applies the In predicate on the "max_pending_parents" field.
func MaxPendingParentsIn(vs ...int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldIn(FieldMaxPendingParents, vs...))
}

// MaxPendingParentsNotIn applies the NotIn predicate on the "max_pending_parents" field.
func MaxPendingParentsNotIn(vs ...int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldNotIn(FieldMaxPendingParents, vs...))
}

// MaxPendingParentsGT applies the GT predicate on the "max_pending_parents" field.
func MaxPendingParentsGT(v int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldGT(FieldMaxPendingParents, v))
}

// MaxPendingParentsGTE applies the GTE predicate on the "max_pending_parents" field.
func MaxPendingParentsGTE(v int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldGTE(FieldMaxPendingParents, v))
}

// MaxPendingParentsLT applies the LT predicate on the "max_pending_parents" field.
func MaxPendingParentsLT(v int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldLT(FieldMaxPendingParents, v))
}

// MaxPendingParentsLTE applies the LTE predicate on the "max_pending_parents" field.
func MaxPendingParentsLTE(v int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldLTE(FieldMaxPendingParents, v))
}

// MaxPendingParentsIsNil applies the IsNil predicate on the "max_pending_parents" field.
func MaxPendingParentsIsNil() predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldIsNull(FieldMaxPendingParents))
}

// MaxPendingParentsNotNil applies the NotNil predicate on the "max_pending_parents" field.
func MaxPendingParentsNotNil() predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldNotNull(FieldMaxPendingParents))
}

// MaxPendingChildrenEQ applies the EQ predicate on the "max_pending_children" field.
func MaxPendingChildrenEQ(v int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldEQ(FieldMaxPendingChildren, v))
}

// MaxPendingChildrenNEQ applies the NEQ predicate on the "max_pending_children" field.
func MaxPendingChildrenNEQ(v int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldNEQ(FieldMaxPendingChildren, v))
}

// MaxPendingChildrenIn applies the In predicate on the "max_pending_children" field.
func MaxPendingChildrenIn(vs ...int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldIn(FieldMaxPendingChildren, vs...))
}

// MaxPendingChildrenNotIn applies the NotIn predicate on the "max_pending_children" field.
func MaxPendingChildrenNotIn(vs ...int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldNotIn(FieldMaxPendingChildren, vs...))
}

// MaxPendingChildrenGT applies the GT predicate on the "max_pending_children" field.
func MaxPendingChildrenGT(v int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldGT(FieldMaxPendingChildren, v))
}

// MaxPendingChildrenGTE applies the GTE predicate on the "max_pending_children" field.
func MaxPendingChildrenGTE(v int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldGTE(FieldMaxPendingChildren, v))
}

// MaxPendingChildrenLT applies the LT predicate on the "max_pending_children" field.
func MaxPendingChildrenLT(v int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldLT(FieldMaxPendingChildren, v))
}

// MaxPendingChildrenLTE applies the LTE predicate on the "max_pending_children" field.
func MaxPendingChildrenLTE(v int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldLTE(FieldMaxPendingChildren, v))
}

// MaxPendingChildrenIsNil applies the IsNil predicate on the "max_pending_children" field.
func MaxPendingChildrenIsNil() predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldIsNull(FieldMaxPendingChildren))
}

// MaxPendingChildrenNotNil applies the NotNil predicate on the "max_pending_children" field.
func MaxPendingChildrenNotNil() predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldNotNull(FieldMaxPendingChildren))
}

// CooldownSecondsEQ applies the EQ predicate on the "cooldown_seconds" field.
func CooldownSecondsEQ(v int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldEQ(FieldCooldownSeconds, v))
}

// CooldownSecondsNEQ applies the NEQ predicate on the "cooldown_seconds" field.
func CooldownSecondsNEQ(v int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldNEQ(FieldCooldownSeconds, v))
}

// CooldownSecondsIn applies the In predicate on the "cooldown_seconds" field.
func CooldownSecondsIn(vs ...int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldIn(FieldCooldownSeconds, vs...))
}

// CooldownSecondsNotIn applies the NotIn predicate on the "cooldown_seconds" field.
func CooldownSecondsNotIn(vs ...int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldNotIn(FieldCooldownSeconds, vs...))
}

// CooldownSecondsGT applies the GT predicate on the "cooldown_seconds" field.
func CooldownSecondsGT(v int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldGT(FieldCooldownSeconds, v))
}

// CooldownSecondsGTE applies the GTE predicate on the "cooldown_seconds" field.
func CooldownSecondsGTE(v int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldGTE(FieldCooldownSeconds, v))
}

// CooldownSecondsLT applies the LT predicate on the "cooldown_seconds" field.
func CooldownSecondsLT(v int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldLT(FieldCooldownSeconds, v))
}

// CooldownSecondsLTE applies the LTE predicate on the "cooldown_seconds" field.
func CooldownSecondsLTE(v int) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldLTE(FieldCooldownSeconds, v))
}

// CooldownSecondsIsNil applies the IsNil predicate on the "cooldown_seconds" field.
func CooldownSecondsIsNil() predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldIsNull(FieldCooldownSeconds))
}

// CooldownSecondsNotNil applies the NotNil predicate on the "cooldown_seconds" field.
func CooldownSecondsNotNil() predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldNotNull(FieldCooldownSeconds))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldContainsFold(FieldReason, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RateLimitUserOverride) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RateLimitUserOverride) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RateLimitUserOverride) predicate.RateLimitUserOverride {
	return predicate.RateLimitUserOverride(sql.NotPredicates(p))
}
