// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"kv-shepherd.io/shepherd/ent/approvalpolicy"
)

// ApprovalPolicy is the model entity for the ApprovalPolicy schema.
type ApprovalPolicy struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// EnvironmentType holds the value of the "environment_type" field.
	EnvironmentType approvalpolicy.EnvironmentType `json:"environment_type,omitempty"`
	// Operation holds the value of the "operation" field.
	Operation approvalpolicy.Operation `json:"operation,omitempty"`
	// RequiresApproval holds the value of the "requires_approval" field.
	RequiresApproval bool `json:"requires_approval,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority int `json:"priority,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy    string `json:"created_by,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ApprovalPolicy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case approvalpolicy.FieldRequiresApproval, approvalpolicy.FieldEnabled:
			values[i] = new(sql.NullBool)
		case approvalpolicy.FieldPriority:
			values[i] = new(sql.NullInt64)
		case approvalpolicy.FieldID, approvalpolicy.FieldName, approvalpolicy.FieldDescription, approvalpolicy.FieldEnvironmentType, approvalpolicy.FieldOperation, approvalpolicy.FieldCreatedBy:
			values[i] = new(sql.NullString)
		case approvalpolicy.FieldCreatedAt, approvalpolicy.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ApprovalPolicy fields.
func (_m *ApprovalPolicy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case approvalpolicy.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case approvalpolicy.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case approvalpolicy.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case approvalpolicy.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case approvalpolicy.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case approvalpolicy.FieldEnvironmentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field environment_type", values[i])
			} else if value.Valid {
				_m.EnvironmentType = approvalpolicy.EnvironmentType(value.String)
			}
		case approvalpolicy.FieldOperation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation", values[i])
			} else if value.Valid {
				_m.Operation = approvalpolicy.Operation(value.String)
			}
		case approvalpolicy.FieldRequiresApproval:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field requires_approval", values[i])
			} else if value.Valid {
				_m.RequiresApproval = value.Bool
			}
		case approvalpolicy.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case approvalpolicy.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case approvalpolicy.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ApprovalPolicy.
// This includes values selected through modifiers, order, etc.
func (_m *ApprovalPolicy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ApprovalPolicy.
// Note that you need to call ApprovalPolicy.Unwrap() before calling this method if this ApprovalPolicy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ApprovalPolicy) Update() *ApprovalPolicyUpdateOne {
	return NewApprovalPolicyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ApprovalPolicy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ApprovalPolicy) Unwrap() *ApprovalPolicy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ApprovalPolicy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ApprovalPolicy) String() string {
	var builder strings.Builder
	builder.WriteString("ApprovalPolicy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("environment_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.EnvironmentType))
	builder.WriteString(", ")
	builder.WriteString("operation=")
	builder.WriteString(fmt.Sprintf("%v", _m.Operation))
	builder.WriteString(", ")
	builder.WriteString("requires_approval=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequiresApproval))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteByte(')')
	return builder.String()
}

// ApprovalPolicies is a parsable slice of ApprovalPolicy.
type ApprovalPolicies []*ApprovalPolicy
