// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"kv-shepherd.io/shepherd/ent/cluster"
)

// Cluster is the model entity for the Cluster schema.
type Cluster struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// APIServerURL holds the value of the "api_server_url" field.
	APIServerURL string `json:"api_server_url,omitempty"`
	// EncryptedKubeconfig holds the value of the "encrypted_kubeconfig" field.
	EncryptedKubeconfig []byte `json:"-"`
	// EncryptionKeyID holds the value of the "encryption_key_id" field.
	EncryptionKeyID string `json:"encryption_key_id,omitempty"`
	// Status holds the value of the "status" field.
	Status cluster.Status `json:"status,omitempty"`
	// KubevirtVersion holds the value of the "kubevirt_version" field.
	KubevirtVersion string `json:"kubevirt_version,omitempty"`
	// EnabledFeatures holds the value of the "enabled_features" field.
	EnabledFeatures []string `json:"enabled_features,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// Cluster environment type (ADR-0015 §1, §15)
	Environment cluster.Environment `json:"environment,omitempty"`
	// Auto-detected StorageClass list from cluster (ADR-0015 §8)
	StorageClasses []string `json:"storage_classes,omitempty"`
	// Admin-specified default StorageClass
	DefaultStorageClass string `json:"default_storage_class,omitempty"`
	// Last StorageClass detection timestamp
	StorageClassesUpdatedAt *time.Time `json:"storage_classes_updated_at,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled      bool `json:"enabled,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Cluster) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cluster.FieldEncryptedKubeconfig, cluster.FieldEnabledFeatures, cluster.FieldStorageClasses:
			values[i] = new([]byte)
		case cluster.FieldEnabled:
			values[i] = new(sql.NullBool)
		case cluster.FieldID, cluster.FieldName, cluster.FieldDisplayName, cluster.FieldAPIServerURL, cluster.FieldEncryptionKeyID, cluster.FieldStatus, cluster.FieldKubevirtVersion, cluster.FieldCreatedBy, cluster.FieldEnvironment, cluster.FieldDefaultStorageClass:
			values[i] = new(sql.NullString)
		case cluster.FieldCreatedAt, cluster.FieldUpdatedAt, cluster.FieldStorageClassesUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Cluster fields.
func (_m *Cluster) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cluster.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case cluster.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case cluster.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case cluster.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case cluster.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case cluster.FieldAPIServerURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_server_url", values[i])
			} else if value.Valid {
				_m.APIServerURL = value.String
			}
		case cluster.FieldEncryptedKubeconfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field encrypted_kubeconfig", values[i])
			} else if value != nil {
				_m.EncryptedKubeconfig = *value
			}
		case cluster.FieldEncryptionKeyID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field encryption_key_id", values[i])
			} else if value.Valid {
				_m.EncryptionKeyID = value.String
			}
		case cluster.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = cluster.Status(value.String)
			}
		case cluster.FieldKubevirtVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kubevirt_version", values[i])
			} else if value.Valid {
				_m.KubevirtVersion = value.String
			}
		case cluster.FieldEnabledFeatures:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field enabled_features", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.EnabledFeatures); err != nil {
					return fmt.Errorf("unmarshal field enabled_features: %w", err)
				}
			}
		case cluster.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case cluster.FieldEnvironment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field environment", values[i])
			} else if value.Valid {
				_m.Environment = cluster.Environment(value.String)
			}
		case cluster.FieldStorageClasses:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field storage_classes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.StorageClasses); err != nil {
					return fmt.Errorf("unmarshal field storage_classes: %w", err)
				}
			}
		case cluster.FieldDefaultStorageClass:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_storage_class", values[i])
			} else if value.Valid {
				_m.DefaultStorageClass = value.String
			}
		case cluster.FieldStorageClassesUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field storage_classes_updated_at", values[i])
			} else if value.Valid {
				_m.StorageClassesUpdatedAt = new(time.Time)
				*_m.StorageClassesUpdatedAt = value.Time
			}
		case cluster.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Cluster.
// This includes values selected through modifiers, order, etc.
func (_m *Cluster) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Cluster.
// Note that you need to call Cluster.Unwrap() before calling this method if this Cluster
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Cluster) Update() *ClusterUpdateOne {
	return NewClusterClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Cluster entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Cluster) Unwrap() *Cluster {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Cluster is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Cluster) String() string {
	var builder strings.Builder
	builder.WriteString("Cluster(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("api_server_url=")
	builder.WriteString(_m.APIServerURL)
	builder.WriteString(", ")
	builder.WriteString("encrypted_kubeconfig=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("encryption_key_id=")
	builder.WriteString(_m.EncryptionKeyID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("kubevirt_version=")
	builder.WriteString(_m.KubevirtVersion)
	builder.WriteString(", ")
	builder.WriteString("enabled_features=")
	builder.WriteString(fmt.Sprintf("%v", _m.EnabledFeatures))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("environment=")
	builder.WriteString(fmt.Sprintf("%v", _m.Environment))
	builder.WriteString(", ")
	builder.WriteString("storage_classes=")
	builder.WriteString(fmt.Sprintf("%v", _m.StorageClasses))
	builder.WriteString(", ")
	builder.WriteString("default_storage_class=")
	builder.WriteString(_m.DefaultStorageClass)
	builder.WriteString(", ")
	if v := _m.StorageClassesUpdatedAt; v != nil {
		builder.WriteString("storage_classes_updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteByte(')')
	return builder.String()
}

// Clusters is a parsable slice of Cluster.
type Clusters []*Cluster
