// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"kv-shepherd.io/shepherd/ent/directorysyncjob"
)

// DirectorySyncJobCreate is the builder for creating a DirectorySyncJob entity.
type DirectorySyncJobCreate struct {
	config
	mutation *DirectorySyncJobMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *DirectorySyncJobCreate) SetCreatedAt(v time.Time) *DirectorySyncJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DirectorySyncJobCreate) SetNillableCreatedAt(v *time.Time) *DirectorySyncJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DirectorySyncJobCreate) SetUpdatedAt(v time.Time) *DirectorySyncJobCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DirectorySyncJobCreate) SetNillableUpdatedAt(v *time.Time) *DirectorySyncJobCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAuthProviderID sets the "auth_provider_id" field.
func (_c *DirectorySyncJobCreate) SetAuthProviderID(v string) *DirectorySyncJobCreate {
	_c.mutation.SetAuthProviderID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *DirectorySyncJobCreate) SetStatus(v directorysyncjob.Status) *DirectorySyncJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DirectorySyncJobCreate) SetNillableStatus(v *directorysyncjob.Status) *DirectorySyncJobCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRequestSnapshot sets the "request_snapshot" field.
func (_c *DirectorySyncJobCreate) SetRequestSnapshot(v map[string]interface{}) *DirectorySyncJobCreate {
	_c.mutation.SetRequestSnapshot(v)
	return _c
}

// SetConflictResolution sets the "conflict_resolution" field.
func (_c *DirectorySyncJobCreate) SetConflictResolution(v string) *DirectorySyncJobCreate {
	_c.mutation.SetConflictResolution(v)
	return _c
}

// SetNillableConflictResolution sets the "conflict_resolution" field if the given value is not nil.
func (_c *DirectorySyncJobCreate) SetNillableConflictResolution(v *string) *DirectorySyncJobCreate {
	if v != nil {
		_c.SetConflictResolution(*v)
	}
	return _c
}

// SetSyncMode sets the "sync_mode" field.
func (_c *DirectorySyncJobCreate) SetSyncMode(v directorysyncjob.SyncMode) *DirectorySyncJobCreate {
	_c.mutation.SetSyncMode(v)
	return _c
}

// SetNillableSyncMode sets the "sync_mode" field if the given value is not nil.
func (_c *DirectorySyncJobCreate) SetNillableSyncMode(v *directorysyncjob.SyncMode) *DirectorySyncJobCreate {
	if v != nil {
		_c.SetSyncMode(*v)
	}
	return _c
}

// SetJoinKeyType sets the "join_key_type" field.
func (_c *DirectorySyncJobCreate) SetJoinKeyType(v string) *DirectorySyncJobCreate {
	_c.mutation.SetJoinKeyType(v)
	return _c
}

// SetNillableJoinKeyType sets the "join_key_type" field if the given value is not nil.
func (_c *DirectorySyncJobCreate) SetNillableJoinKeyType(v *string) *DirectorySyncJobCreate {
	if v != nil {
		_c.SetJoinKeyType(*v)
	}
	return _c
}

// SetTotalEntries sets the "total_entries" field.
func (_c *DirectorySyncJobCreate) SetTotalEntries(v int) *DirectorySyncJobCreate {
	_c.mutation.SetTotalEntries(v)
	return _c
}

// SetNillableTotalEntries sets the "total_entries" field if the given value is not nil.
func (_c *DirectorySyncJobCreate) SetNillableTotalEntries(v *int) *DirectorySyncJobCreate {
	if v != nil {
		_c.SetTotalEntries(*v)
	}
	return _c
}

// SetCreateCount sets the "create_count" field.
func (_c *DirectorySyncJobCreate) SetCreateCount(v int) *DirectorySyncJobCreate {
	_c.mutation.SetCreateCount(v)
	return _c
}

// SetNillableCreateCount sets the "create_count" field if the given value is not nil.
func (_c *DirectorySyncJobCreate) SetNillableCreateCount(v *int) *DirectorySyncJobCreate {
	if v != nil {
		_c.SetCreateCount(*v)
	}
	return _c
}

// SetUpdateCount sets the "update_count" field.
func (_c *DirectorySyncJobCreate) SetUpdateCount(v int) *DirectorySyncJobCreate {
	_c.mutation.SetUpdateCount(v)
	return _c
}

// SetNillableUpdateCount sets the "update_count" field if the given value is not nil.
func (_c *DirectorySyncJobCreate) SetNillableUpdateCount(v *int) *DirectorySyncJobCreate {
	if v != nil {
		_c.SetUpdateCount(*v)
	}
	return _c
}

// SetBlockedCount sets the "blocked_count" field.
func (_c *DirectorySyncJobCreate) SetBlockedCount(v int) *DirectorySyncJobCreate {
	_c.mutation.SetBlockedCount(v)
	return _c
}

// SetNillableBlockedCount sets the "blocked_count" field if the given value is not nil.
func (_c *DirectorySyncJobCreate) SetNillableBlockedCount(v *int) *DirectorySyncJobCreate {
	if v != nil {
		_c.SetBlockedCount(*v)
	}
	return _c
}

// SetErrorCount sets the "error_count" field.
func (_c *DirectorySyncJobCreate) SetErrorCount(v int) *DirectorySyncJobCreate {
	_c.mutation.SetErrorCount(v)
	return _c
}

// SetNillableErrorCount sets the "error_count" field if the given value is not nil.
func (_c *DirectorySyncJobCreate) SetNillableErrorCount(v *int) *DirectorySyncJobCreate {
	if v != nil {
		_c.SetErrorCount(*v)
	}
	return _c
}

// SetErrors sets the "errors" field.
func (_c *DirectorySyncJobCreate) SetErrors(v []string) *DirectorySyncJobCreate {
	_c.mutation.SetErrors(v)
	return _c
}

// SetTriggeredBy sets the "triggered_by" field.
func (_c *DirectorySyncJobCreate) SetTriggeredBy(v string) *DirectorySyncJobCreate {
	_c.mutation.SetTriggeredBy(v)
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *DirectorySyncJobCreate) SetStartedAt(v time.Time) *DirectorySyncJobCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *DirectorySyncJobCreate) SetNillableStartedAt(v *time.Time) *DirectorySyncJobCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *DirectorySyncJobCreate) SetCompletedAt(v time.Time) *DirectorySyncJobCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *DirectorySyncJobCreate) SetNillableCompletedAt(v *time.Time) *DirectorySyncJobCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DirectorySyncJobCreate) SetID(v string) *DirectorySyncJobCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the DirectorySyncJobMutation object of the builder.
func (_c *DirectorySyncJobCreate) Mutation() *DirectorySyncJobMutation {
	return _c.mutation
}

// Save creates the DirectorySyncJob in the database.
func (_c *DirectorySyncJobCreate) Save(ctx context.Context) (*DirectorySyncJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DirectorySyncJobCreate) SaveX(ctx context.Context) *DirectorySyncJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DirectorySyncJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DirectorySyncJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DirectorySyncJobCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := directorysyncjob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := directorysyncjob.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := directorysyncjob.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ConflictResolution(); !ok {
		v := directorysyncjob.DefaultConflictResolution
		_c.mutation.SetConflictResolution(v)
	}
	if _, ok := _c.mutation.SyncMode(); !ok {
		v := directorysyncjob.DefaultSyncMode
		_c.mutation.SetSyncMode(v)
	}
	if _, ok := _c.mutation.JoinKeyType(); !ok {
		v := directorysyncjob.DefaultJoinKeyType
		_c.mutation.SetJoinKeyType(v)
	}
	if _, ok := _c.mutation.TotalEntries(); !ok {
		v := directorysyncjob.DefaultTotalEntries
		_c.mutation.SetTotalEntries(v)
	}
	if _, ok := _c.mutation.CreateCount(); !ok {
		v := directorysyncjob.DefaultCreateCount
		_c.mutation.SetCreateCount(v)
	}
	if _, ok := _c.mutation.UpdateCount(); !ok {
		v := directorysyncjob.DefaultUpdateCount
		_c.mutation.SetUpdateCount(v)
	}
	if _, ok := _c.mutation.BlockedCount(); !ok {
		v := directorysyncjob.DefaultBlockedCount
		_c.mutation.SetBlockedCount(v)
	}
	if _, ok := _c.mutation.ErrorCount(); !ok {
		v := directorysyncjob.DefaultErrorCount
		_c.mutation.SetErrorCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DirectorySyncJobCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DirectorySyncJob.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DirectorySyncJob.updated_at"`)}
	}
	if _, ok := _c.mutation.AuthProviderID(); !ok {
		return &ValidationError{Name: "auth_provider_id", err: errors.New(`ent: missing required field "DirectorySyncJob.auth_provider_id"`)}
	}
	if v, ok := _c.mutation.AuthProviderID(); ok {
		if err := directorysyncjob.AuthProviderIDValidator(v); err != nil {
			return &ValidationError{Name: "auth_provider_id", err: fmt.Errorf(`ent: validator failed for field "DirectorySyncJob.auth_provider_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DirectorySyncJob.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := directorysyncjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DirectorySyncJob.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestSnapshot(); !ok {
		return &ValidationError{Name: "request_snapshot", err: errors.New(`ent: missing required field "DirectorySyncJob.request_snapshot"`)}
	}
	if _, ok := _c.mutation.ConflictResolution(); !ok {
		return &ValidationError{Name: "conflict_resolution", err: errors.New(`ent: missing required field "DirectorySyncJob.conflict_resolution"`)}
	}
	if _, ok := _c.mutation.SyncMode(); !ok {
		return &ValidationError{Name: "sync_mode", err: errors.New(`ent: missing required field "DirectorySyncJob.sync_mode"`)}
	}
	if v, ok := _c.mutation.SyncMode(); ok {
		if err := directorysyncjob.SyncModeValidator(v); err != nil {
			return &ValidationError{Name: "sync_mode", err: fmt.Errorf(`ent: validator failed for field "DirectorySyncJob.sync_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.JoinKeyType(); !ok {
		return &ValidationError{Name: "join_key_type", err: errors.New(`ent: missing required field "DirectorySyncJob.join_key_type"`)}
	}
	if _, ok := _c.mutation.TotalEntries(); !ok {
		return &ValidationError{Name: "total_entries", err: errors.New(`ent: missing required field "DirectorySyncJob.total_entries"`)}
	}
	if _, ok := _c.mutation.CreateCount(); !ok {
		return &ValidationError{Name: "create_count", err: errors.New(`ent: missing required field "DirectorySyncJob.create_count"`)}
	}
	if _, ok := _c.mutation.UpdateCount(); !ok {
		return &ValidationError{Name: "update_count", err: errors.New(`ent: missing required field "DirectorySyncJob.update_count"`)}
	}
	if _, ok := _c.mutation.BlockedCount(); !ok {
		return &ValidationError{Name: "blocked_count", err: errors.New(`ent: missing required field "DirectorySyncJob.blocked_count"`)}
	}
	if _, ok := _c.mutation.ErrorCount(); !ok {
		return &ValidationError{Name: "error_count", err: errors.New(`ent: missing required field "DirectorySyncJob.error_count"`)}
	}
	if _, ok := _c.mutation.TriggeredBy(); !ok {
		return &ValidationError{Name: "triggered_by", err: errors.New(`ent: missing required field "DirectorySyncJob.triggered_by"`)}
	}
	if v, ok := _c.mutation.TriggeredBy(); ok {
		if err := directorysyncjob.TriggeredByValidator(v); err != nil {
			return &ValidationError{Name: "triggered_by", err: fmt.Errorf(`ent: validator failed for field "DirectorySyncJob.triggered_by": %w`, err)}
		}
	}
	return nil
}

func (_c *DirectorySyncJobCreate) sqlSave(ctx context.Context) (*DirectorySyncJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DirectorySyncJob.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DirectorySyncJobCreate) createSpec() (*DirectorySyncJob, *sqlgraph.CreateSpec) {
	var (
		_node = &DirectorySyncJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(directorysyncjob.Table, sqlgraph.NewFieldSpec(directorysyncjob.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(directorysyncjob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(directorysyncjob.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AuthProviderID(); ok {
		_spec.SetField(directorysyncjob.FieldAuthProviderID, field.TypeString, value)
		_node.AuthProviderID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(directorysyncjob.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RequestSnapshot(); ok {
		_spec.SetField(directorysyncjob.FieldRequestSnapshot, field.TypeJSON, value)
		_node.RequestSnapshot = value
	}
	if value, ok := _c.mutation.ConflictResolution(); ok {
		_spec.SetField(directorysyncjob.FieldConflictResolution, field.TypeString, value)
		_node.ConflictResolution = value
	}
	if value, ok := _c.mutation.SyncMode(); ok {
		_spec.SetField(directorysyncjob.FieldSyncMode, field.TypeEnum, value)
		_node.SyncMode = value
	}
	if value, ok := _c.mutation.JoinKeyType(); ok {
		_spec.SetField(directorysyncjob.FieldJoinKeyType, field.TypeString, value)
		_node.JoinKeyType = value
	}
	if value, ok := _c.mutation.TotalEntries(); ok {
		_spec.SetField(directorysyncjob.FieldTotalEntries, field.TypeInt, value)
		_node.TotalEntries = value
	}
	if value, ok := _c.mutation.CreateCount(); ok {
		_spec.SetField(directorysyncjob.FieldCreateCount, field.TypeInt, value)
		_node.CreateCount = value
	}
	if value, ok := _c.mutation.UpdateCount(); ok {
		_spec.SetField(directorysyncjob.FieldUpdateCount, field.TypeInt, value)
		_node.UpdateCount = value
	}
	if value, ok := _c.mutation.BlockedCount(); ok {
		_spec.SetField(directorysyncjob.FieldBlockedCount, field.TypeInt, value)
		_node.BlockedCount = value
	}
	if value, ok := _c.mutation.ErrorCount(); ok {
		_spec.SetField(directorysyncjob.FieldErrorCount, field.TypeInt, value)
		_node.ErrorCount = value
	}
	if value, ok := _c.mutation.Errors(); ok {
		_spec.SetField(directorysyncjob.FieldErrors, field.TypeJSON, value)
		_node.Errors = value
	}
	if value, ok := _c.mutation.TriggeredBy(); ok {
		_spec.SetField(directorysyncjob.FieldTriggeredBy, field.TypeString, value)
		_node.TriggeredBy = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(directorysyncjob.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(directorysyncjob.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	return _node, _spec
}

// DirectorySyncJobCreateBulk is the builder for creating many DirectorySyncJob entities in bulk.
type DirectorySyncJobCreateBulk struct {
	config
	err      error
	builders []*DirectorySyncJobCreate
}

// Save creates the DirectorySyncJob entities in the database.
func (_c *DirectorySyncJobCreateBulk) Save(ctx context.Context) ([]*DirectorySyncJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DirectorySyncJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DirectorySyncJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DirectorySyncJobCreateBulk) SaveX(ctx context.Context) []*DirectorySyncJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DirectorySyncJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DirectorySyncJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
