// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"kv-shepherd.io/shepherd/ent/domainevent"
)

// DomainEventCreate is the builder for creating a DomainEvent entity.
type DomainEventCreate struct {
	config
	mutation *DomainEventMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *DomainEventCreate) SetCreatedAt(v time.Time) *DomainEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DomainEventCreate) SetNillableCreatedAt(v *time.Time) *DomainEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *DomainEventCreate) SetEventType(v string) *DomainEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetAggregateType sets the "aggregate_type" field.
func (_c *DomainEventCreate) SetAggregateType(v string) *DomainEventCreate {
	_c.mutation.SetAggregateType(v)
	return _c
}

// SetAggregateID sets the "aggregate_id" field.
func (_c *DomainEventCreate) SetAggregateID(v string) *DomainEventCreate {
	_c.mutation.SetAggregateID(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *DomainEventCreate) SetPayload(v []byte) *DomainEventCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *DomainEventCreate) SetStatus(v domainevent.Status) *DomainEventCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DomainEventCreate) SetNillableStatus(v *domainevent.Status) *DomainEventCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *DomainEventCreate) SetCreatedBy(v string) *DomainEventCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetArchivedAt sets the "archived_at" field.
func (_c *DomainEventCreate) SetArchivedAt(v time.Time) *DomainEventCreate {
	_c.mutation.SetArchivedAt(v)
	return _c
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_c *DomainEventCreate) SetNillableArchivedAt(v *time.Time) *DomainEventCreate {
	if v != nil {
		_c.SetArchivedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DomainEventCreate) SetID(v string) *DomainEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the DomainEventMutation object of the builder.
func (_c *DomainEventCreate) Mutation() *DomainEventMutation {
	return _c.mutation
}

// Save creates the DomainEvent in the database.
func (_c *DomainEventCreate) Save(ctx context.Context) (*DomainEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DomainEventCreate) SaveX(ctx context.Context) *DomainEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DomainEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DomainEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DomainEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := domainevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := domainevent.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DomainEventCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DomainEvent.created_at"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "DomainEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := domainevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "DomainEvent.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AggregateType(); !ok {
		return &ValidationError{Name: "aggregate_type", err: errors.New(`ent: missing required field "DomainEvent.aggregate_type"`)}
	}
	if v, ok := _c.mutation.AggregateType(); ok {
		if err := domainevent.AggregateTypeValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_type", err: fmt.Errorf(`ent: validator failed for field "DomainEvent.aggregate_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AggregateID(); !ok {
		return &ValidationError{Name: "aggregate_id", err: errors.New(`ent: missing required field "DomainEvent.aggregate_id"`)}
	}
	if v, ok := _c.mutation.AggregateID(); ok {
		if err := domainevent.AggregateIDValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_id", err: fmt.Errorf(`ent: validator failed for field "DomainEvent.aggregate_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "DomainEvent.payload"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DomainEvent.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := domainevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DomainEvent.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "DomainEvent.created_by"`)}
	}
	if v, ok := _c.mutation.CreatedBy(); ok {
		if err := domainevent.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "DomainEvent.created_by": %w`, err)}
		}
	}
	return nil
}

func (_c *DomainEventCreate) sqlSave(ctx context.Context) (*DomainEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DomainEvent.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DomainEventCreate) createSpec() (*DomainEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &DomainEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(domainevent.Table, sqlgraph.NewFieldSpec(domainevent.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(domainevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(domainevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.AggregateType(); ok {
		_spec.SetField(domainevent.FieldAggregateType, field.TypeString, value)
		_node.AggregateType = value
	}
	if value, ok := _c.mutation.AggregateID(); ok {
		_spec.SetField(domainevent.FieldAggregateID, field.TypeString, value)
		_node.AggregateID = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(domainevent.FieldPayload, field.TypeBytes, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(domainevent.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(domainevent.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.ArchivedAt(); ok {
		_spec.SetField(domainevent.FieldArchivedAt, field.TypeTime, value)
		_node.ArchivedAt = &value
	}
	return _node, _spec
}

// DomainEventCreateBulk is the builder for creating many DomainEvent entities in bulk.
type DomainEventCreateBulk struct {
	config
	err      error
	builders []*DomainEventCreate
}

// Save creates the DomainEvent entities in the database.
func (_c *DomainEventCreateBulk) Save(ctx context.Context) ([]*DomainEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DomainEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DomainEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DomainEventCreateBulk) SaveX(ctx context.Context) []*DomainEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DomainEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DomainEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
