// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"kv-shepherd.io/shepherd/ent/externalcohort"
)

// ExternalCohort is the model entity for the ExternalCohort schema.
type ExternalCohort struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ProviderID holds the value of the "provider_id" field.
	ProviderID string `json:"provider_id,omitempty"`
	// CohortKind holds the value of the "cohort_kind" field.
	CohortKind string `json:"cohort_kind,omitempty"`
	// CohortKey holds the value of the "cohort_key" field.
	CohortKey string `json:"cohort_key,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// SourceField holds the value of the "source_field" field.
	SourceField string `json:"source_field,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// LastSyncedAt holds the value of the "last_synced_at" field.
	LastSyncedAt *time.Time `json:"last_synced_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExternalCohort) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case externalcohort.FieldID, externalcohort.FieldProviderID, externalcohort.FieldCohortKind, externalcohort.FieldCohortKey, externalcohort.FieldDisplayName, externalcohort.FieldSourceField, externalcohort.FieldDescription:
			values[i] = new(sql.NullString)
		case externalcohort.FieldCreatedAt, externalcohort.FieldUpdatedAt, externalcohort.FieldLastSyncedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExternalCohort fields.
func (_m *ExternalCohort) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case externalcohort.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case externalcohort.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case externalcohort.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case externalcohort.FieldProviderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_id", values[i])
			} else if value.Valid {
				_m.ProviderID = value.String
			}
		case externalcohort.FieldCohortKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cohort_kind", values[i])
			} else if value.Valid {
				_m.CohortKind = value.String
			}
		case externalcohort.FieldCohortKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cohort_key", values[i])
			} else if value.Valid {
				_m.CohortKey = value.String
			}
		case externalcohort.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case externalcohort.FieldSourceField:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_field", values[i])
			} else if value.Valid {
				_m.SourceField = value.String
			}
		case externalcohort.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case externalcohort.FieldLastSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_synced_at", values[i])
			} else if value.Valid {
				_m.LastSyncedAt = new(time.Time)
				*_m.LastSyncedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExternalCohort.
// This includes values selected through modifiers, order, etc.
func (_m *ExternalCohort) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ExternalCohort.
// Note that you need to call ExternalCohort.Unwrap() before calling this method if this ExternalCohort
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ExternalCohort) Update() *ExternalCohortUpdateOne {
	return NewExternalCohortClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ExternalCohort entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ExternalCohort) Unwrap() *ExternalCohort {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ExternalCohort is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ExternalCohort) String() string {
	var builder strings.Builder
	builder.WriteString("ExternalCohort(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("provider_id=")
	builder.WriteString(_m.ProviderID)
	builder.WriteString(", ")
	builder.WriteString("cohort_kind=")
	builder.WriteString(_m.CohortKind)
	builder.WriteString(", ")
	builder.WriteString("cohort_key=")
	builder.WriteString(_m.CohortKey)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("source_field=")
	builder.WriteString(_m.SourceField)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	if v := _m.LastSyncedAt; v != nil {
		builder.WriteString("last_synced_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ExternalCohorts is a parsable slice of ExternalCohort.
type ExternalCohorts []*ExternalCohort
