// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"kv-shepherd.io/shepherd/ent/externalcohort"
)

// ExternalCohortCreate is the builder for creating a ExternalCohort entity.
type ExternalCohortCreate struct {
	config
	mutation *ExternalCohortMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExternalCohortCreate) SetCreatedAt(v time.Time) *ExternalCohortCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExternalCohortCreate) SetNillableCreatedAt(v *time.Time) *ExternalCohortCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ExternalCohortCreate) SetUpdatedAt(v time.Time) *ExternalCohortCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ExternalCohortCreate) SetNillableUpdatedAt(v *time.Time) *ExternalCohortCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetProviderID sets the "provider_id" field.
func (_c *ExternalCohortCreate) SetProviderID(v string) *ExternalCohortCreate {
	_c.mutation.SetProviderID(v)
	return _c
}

// SetCohortKind sets the "cohort_kind" field.
func (_c *ExternalCohortCreate) SetCohortKind(v string) *ExternalCohortCreate {
	_c.mutation.SetCohortKind(v)
	return _c
}

// SetCohortKey sets the "cohort_key" field.
func (_c *ExternalCohortCreate) SetCohortKey(v string) *ExternalCohortCreate {
	_c.mutation.SetCohortKey(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *ExternalCohortCreate) SetDisplayName(v string) *ExternalCohortCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetSourceField sets the "source_field" field.
func (_c *ExternalCohortCreate) SetSourceField(v string) *ExternalCohortCreate {
	_c.mutation.SetSourceField(v)
	return _c
}

// SetNillableSourceField sets the "source_field" field if the given value is not nil.
func (_c *ExternalCohortCreate) SetNillableSourceField(v *string) *ExternalCohortCreate {
	if v != nil {
		_c.SetSourceField(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *ExternalCohortCreate) SetDescription(v string) *ExternalCohortCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ExternalCohortCreate) SetNillableDescription(v *string) *ExternalCohortCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_c *ExternalCohortCreate) SetLastSyncedAt(v time.Time) *ExternalCohortCreate {
	_c.mutation.SetLastSyncedAt(v)
	return _c
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_c *ExternalCohortCreate) SetNillableLastSyncedAt(v *time.Time) *ExternalCohortCreate {
	if v != nil {
		_c.SetLastSyncedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ExternalCohortCreate) SetID(v string) *ExternalCohortCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ExternalCohortMutation object of the builder.
func (_c *ExternalCohortCreate) Mutation() *ExternalCohortMutation {
	return _c.mutation
}

// Save creates the ExternalCohort in the database.
func (_c *ExternalCohortCreate) Save(ctx context.Context) (*ExternalCohort, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExternalCohortCreate) SaveX(ctx context.Context) *ExternalCohort {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExternalCohortCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExternalCohortCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExternalCohortCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := externalcohort.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := externalcohort.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExternalCohortCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ExternalCohort.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ExternalCohort.updated_at"`)}
	}
	if _, ok := _c.mutation.ProviderID(); !ok {
		return &ValidationError{Name: "provider_id", err: errors.New(`ent: missing required field "ExternalCohort.provider_id"`)}
	}
	if v, ok := _c.mutation.ProviderID(); ok {
		if err := externalcohort.ProviderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_id", err: fmt.Errorf(`ent: validator failed for field "ExternalCohort.provider_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CohortKind(); !ok {
		return &ValidationError{Name: "cohort_kind", err: errors.New(`ent: missing required field "ExternalCohort.cohort_kind"`)}
	}
	if v, ok := _c.mutation.CohortKind(); ok {
		if err := externalcohort.CohortKindValidator(v); err != nil {
			return &ValidationError{Name: "cohort_kind", err: fmt.Errorf(`ent: validator failed for field "ExternalCohort.cohort_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CohortKey(); !ok {
		return &ValidationError{Name: "cohort_key", err: errors.New(`ent: missing required field "ExternalCohort.cohort_key"`)}
	}
	if v, ok := _c.mutation.CohortKey(); ok {
		if err := externalcohort.CohortKeyValidator(v); err != nil {
			return &ValidationError{Name: "cohort_key", err: fmt.Errorf(`ent: validator failed for field "ExternalCohort.cohort_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "ExternalCohort.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := externalcohort.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "ExternalCohort.display_name": %w`, err)}
		}
	}
	return nil
}

func (_c *ExternalCohortCreate) sqlSave(ctx context.Context) (*ExternalCohort, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ExternalCohort.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExternalCohortCreate) createSpec() (*ExternalCohort, *sqlgraph.CreateSpec) {
	var (
		_node = &ExternalCohort{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(externalcohort.Table, sqlgraph.NewFieldSpec(externalcohort.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(externalcohort.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(externalcohort.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ProviderID(); ok {
		_spec.SetField(externalcohort.FieldProviderID, field.TypeString, value)
		_node.ProviderID = value
	}
	if value, ok := _c.mutation.CohortKind(); ok {
		_spec.SetField(externalcohort.FieldCohortKind, field.TypeString, value)
		_node.CohortKind = value
	}
	if value, ok := _c.mutation.CohortKey(); ok {
		_spec.SetField(externalcohort.FieldCohortKey, field.TypeString, value)
		_node.CohortKey = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(externalcohort.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.SourceField(); ok {
		_spec.SetField(externalcohort.FieldSourceField, field.TypeString, value)
		_node.SourceField = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(externalcohort.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.LastSyncedAt(); ok {
		_spec.SetField(externalcohort.FieldLastSyncedAt, field.TypeTime, value)
		_node.LastSyncedAt = &value
	}
	return _node, _spec
}

// ExternalCohortCreateBulk is the builder for creating many ExternalCohort entities in bulk.
type ExternalCohortCreateBulk struct {
	config
	err      error
	builders []*ExternalCohortCreate
}

// Save creates the ExternalCohort entities in the database.
func (_c *ExternalCohortCreateBulk) Save(ctx context.Context) ([]*ExternalCohort, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExternalCohort, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExternalCohortMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExternalCohortCreateBulk) SaveX(ctx context.Context) []*ExternalCohort {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExternalCohortCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExternalCohortCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
