// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"kv-shepherd.io/shepherd/ent/externalcohortgrant"
	"kv-shepherd.io/shepherd/ent/predicate"
)

// ExternalCohortGrantDelete is the builder for deleting a ExternalCohortGrant entity.
type ExternalCohortGrantDelete struct {
	config
	hooks    []Hook
	mutation *ExternalCohortGrantMutation
}

// Where appends a list predicates to the ExternalCohortGrantDelete builder.
func (_d *ExternalCohortGrantDelete) Where(ps ...predicate.ExternalCohortGrant) *ExternalCohortGrantDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ExternalCohortGrantDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ExternalCohortGrantDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ExternalCohortGrantDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(externalcohortgrant.Table, sqlgraph.NewFieldSpec(externalcohortgrant.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ExternalCohortGrantDeleteOne is the builder for deleting a single ExternalCohortGrant entity.
type ExternalCohortGrantDeleteOne struct {
	_d *ExternalCohortGrantDelete
}

// Where appends a list predicates to the ExternalCohortGrantDelete builder.
func (_d *ExternalCohortGrantDeleteOne) Where(ps ...predicate.ExternalCohortGrant) *ExternalCohortGrantDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ExternalCohortGrantDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{externalcohortgrant.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ExternalCohortGrantDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
