// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"kv-shepherd.io/shepherd/ent/idpgroupmapping"
	"kv-shepherd.io/shepherd/ent/predicate"
)

// IdPGroupMappingUpdate is the builder for updating IdPGroupMapping entities.
type IdPGroupMappingUpdate struct {
	config
	hooks    []Hook
	mutation *IdPGroupMappingMutation
}

// Where appends a list predicates to the IdPGroupMappingUpdate builder.
func (_u *IdPGroupMappingUpdate) Where(ps ...predicate.IdPGroupMapping) *IdPGroupMappingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IdPGroupMappingUpdate) SetUpdatedAt(v time.Time) *IdPGroupMappingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSyncedGroupID sets the "synced_group_id" field.
func (_u *IdPGroupMappingUpdate) SetSyncedGroupID(v string) *IdPGroupMappingUpdate {
	_u.mutation.SetSyncedGroupID(v)
	return _u
}

// SetNillableSyncedGroupID sets the "synced_group_id" field if the given value is not nil.
func (_u *IdPGroupMappingUpdate) SetNillableSyncedGroupID(v *string) *IdPGroupMappingUpdate {
	if v != nil {
		_u.SetSyncedGroupID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *IdPGroupMappingUpdate) SetRoleID(v string) *IdPGroupMappingUpdate {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *IdPGroupMappingUpdate) SetNillableRoleID(v *string) *IdPGroupMappingUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *IdPGroupMappingUpdate) SetScope(v string) *IdPGroupMappingUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *IdPGroupMappingUpdate) SetNillableScope(v *string) *IdPGroupMappingUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// ClearScope clears the value of the "scope" field.
func (_u *IdPGroupMappingUpdate) ClearScope() *IdPGroupMappingUpdate {
	_u.mutation.ClearScope()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *IdPGroupMappingUpdate) SetCreatedBy(v string) *IdPGroupMappingUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *IdPGroupMappingUpdate) SetNillableCreatedBy(v *string) *IdPGroupMappingUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// Mutation returns the IdPGroupMappingMutation object of the builder.
func (_u *IdPGroupMappingUpdate) Mutation() *IdPGroupMappingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IdPGroupMappingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IdPGroupMappingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IdPGroupMappingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IdPGroupMappingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IdPGroupMappingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := idpgroupmapping.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IdPGroupMappingUpdate) check() error {
	if v, ok := _u.mutation.SyncedGroupID(); ok {
		if err := idpgroupmapping.SyncedGroupIDValidator(v); err != nil {
			return &ValidationError{Name: "synced_group_id", err: fmt.Errorf(`ent: validator failed for field "IdPGroupMapping.synced_group_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RoleID(); ok {
		if err := idpgroupmapping.RoleIDValidator(v); err != nil {
			return &ValidationError{Name: "role_id", err: fmt.Errorf(`ent: validator failed for field "IdPGroupMapping.role_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatedBy(); ok {
		if err := idpgroupmapping.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "IdPGroupMapping.created_by": %w`, err)}
		}
	}
	return nil
}

func (_u *IdPGroupMappingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(idpgroupmapping.Table, idpgroupmapping.Columns, sqlgraph.NewFieldSpec(idpgroupmapping.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(idpgroupmapping.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SyncedGroupID(); ok {
		_spec.SetField(idpgroupmapping.FieldSyncedGroupID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RoleID(); ok {
		_spec.SetField(idpgroupmapping.FieldRoleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(idpgroupmapping.FieldScope, field.TypeString, value)
	}
	if _u.mutation.ScopeCleared() {
		_spec.ClearField(idpgroupmapping.FieldScope, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(idpgroupmapping.FieldCreatedBy, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{idpgroupmapping.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IdPGroupMappingUpdateOne is the builder for updating a single IdPGroupMapping entity.
type IdPGroupMappingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IdPGroupMappingMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IdPGroupMappingUpdateOne) SetUpdatedAt(v time.Time) *IdPGroupMappingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSyncedGroupID sets the "synced_group_id" field.
func (_u *IdPGroupMappingUpdateOne) SetSyncedGroupID(v string) *IdPGroupMappingUpdateOne {
	_u.mutation.SetSyncedGroupID(v)
	return _u
}

// SetNillableSyncedGroupID sets the "synced_group_id" field if the given value is not nil.
func (_u *IdPGroupMappingUpdateOne) SetNillableSyncedGroupID(v *string) *IdPGroupMappingUpdateOne {
	if v != nil {
		_u.SetSyncedGroupID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *IdPGroupMappingUpdateOne) SetRoleID(v string) *IdPGroupMappingUpdateOne {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *IdPGroupMappingUpdateOne) SetNillableRoleID(v *string) *IdPGroupMappingUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *IdPGroupMappingUpdateOne) SetScope(v string) *IdPGroupMappingUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *IdPGroupMappingUpdateOne) SetNillableScope(v *string) *IdPGroupMappingUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// ClearScope clears the value of the "scope" field.
func (_u *IdPGroupMappingUpdateOne) ClearScope() *IdPGroupMappingUpdateOne {
	_u.mutation.ClearScope()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *IdPGroupMappingUpdateOne) SetCreatedBy(v string) *IdPGroupMappingUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *IdPGroupMappingUpdateOne) SetNillableCreatedBy(v *string) *IdPGroupMappingUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// Mutation returns the IdPGroupMappingMutation object of the builder.
func (_u *IdPGroupMappingUpdateOne) Mutation() *IdPGroupMappingMutation {
	return _u.mutation
}

// Where appends a list predicates to the IdPGroupMappingUpdate builder.
func (_u *IdPGroupMappingUpdateOne) Where(ps ...predicate.IdPGroupMapping) *IdPGroupMappingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IdPGroupMappingUpdateOne) Select(field string, fields ...string) *IdPGroupMappingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IdPGroupMapping entity.
func (_u *IdPGroupMappingUpdateOne) Save(ctx context.Context) (*IdPGroupMapping, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IdPGroupMappingUpdateOne) SaveX(ctx context.Context) *IdPGroupMapping {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IdPGroupMappingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IdPGroupMappingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IdPGroupMappingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := idpgroupmapping.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IdPGroupMappingUpdateOne) check() error {
	if v, ok := _u.mutation.SyncedGroupID(); ok {
		if err := idpgroupmapping.SyncedGroupIDValidator(v); err != nil {
			return &ValidationError{Name: "synced_group_id", err: fmt.Errorf(`ent: validator failed for field "IdPGroupMapping.synced_group_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RoleID(); ok {
		if err := idpgroupmapping.RoleIDValidator(v); err != nil {
			return &ValidationError{Name: "role_id", err: fmt.Errorf(`ent: validator failed for field "IdPGroupMapping.role_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatedBy(); ok {
		if err := idpgroupmapping.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "IdPGroupMapping.created_by": %w`, err)}
		}
	}
	return nil
}

func (_u *IdPGroupMappingUpdateOne) sqlSave(ctx context.Context) (_node *IdPGroupMapping, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(idpgroupmapping.Table, idpgroupmapping.Columns, sqlgraph.NewFieldSpec(idpgroupmapping.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IdPGroupMapping.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, idpgroupmapping.FieldID)
		for _, f := range fields {
			if !idpgroupmapping.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != idpgroupmapping.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(idpgroupmapping.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SyncedGroupID(); ok {
		_spec.SetField(idpgroupmapping.FieldSyncedGroupID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RoleID(); ok {
		_spec.SetField(idpgroupmapping.FieldRoleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(idpgroupmapping.FieldScope, field.TypeString, value)
	}
	if _u.mutation.ScopeCleared() {
		_spec.ClearField(idpgroupmapping.FieldScope, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(idpgroupmapping.FieldCreatedBy, field.TypeString, value)
	}
	_node = &IdPGroupMapping{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{idpgroupmapping.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
