// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"kv-shepherd.io/shepherd/ent/idpsyncedgroup"
	"kv-shepherd.io/shepherd/ent/predicate"
)

// IdPSyncedGroupDelete is the builder for deleting a IdPSyncedGroup entity.
type IdPSyncedGroupDelete struct {
	config
	hooks    []Hook
	mutation *IdPSyncedGroupMutation
}

// Where appends a list predicates to the IdPSyncedGroupDelete builder.
func (_d *IdPSyncedGroupDelete) Where(ps ...predicate.IdPSyncedGroup) *IdPSyncedGroupDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *IdPSyncedGroupDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *IdPSyncedGroupDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *IdPSyncedGroupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(idpsyncedgroup.Table, sqlgraph.NewFieldSpec(idpsyncedgroup.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// IdPSyncedGroupDeleteOne is the builder for deleting a single IdPSyncedGroup entity.
type IdPSyncedGroupDeleteOne struct {
	_d *IdPSyncedGroupDelete
}

// Where appends a list predicates to the IdPSyncedGroupDelete builder.
func (_d *IdPSyncedGroupDeleteOne) Where(ps ...predicate.IdPSyncedGroup) *IdPSyncedGroupDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *IdPSyncedGroupDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{idpsyncedgroup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *IdPSyncedGroupDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
