// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"kv-shepherd.io/shepherd/ent/predicate"
	"kv-shepherd.io/shepherd/ent/ratelimituseroverride"
)

// RateLimitUserOverrideUpdate is the builder for updating RateLimitUserOverride entities.
type RateLimitUserOverrideUpdate struct {
	config
	hooks    []Hook
	mutation *RateLimitUserOverrideMutation
}

// Where appends a list predicates to the RateLimitUserOverrideUpdate builder.
func (_u *RateLimitUserOverrideUpdate) Where(ps ...predicate.RateLimitUserOverride) *RateLimitUserOverrideUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RateLimitUserOverrideUpdate) SetUpdatedAt(v time.Time) *RateLimitUserOverrideUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMaxPendingParents sets the "max_pending_parents" field.
func (_u *RateLimitUserOverrideUpdate) SetMaxPendingParents(v int) *RateLimitUserOverrideUpdate {
	_u.mutation.ResetMaxPendingParents()
	_u.mutation.SetMaxPendingParents(v)
	return _u
}

// SetNillableMaxPendingParents sets the "max_pending_parents" field if the given value is not nil.
func (_u *RateLimitUserOverrideUpdate) SetNillableMaxPendingParents(v *int) *RateLimitUserOverrideUpdate {
	if v != nil {
		_u.SetMaxPendingParents(*v)
	}
	return _u
}

// AddMaxPendingParents adds value to the "max_pending_parents" field.
func (_u *RateLimitUserOverrideUpdate) AddMaxPendingParents(v int) *RateLimitUserOverrideUpdate {
	_u.mutation.AddMaxPendingParents(v)
	return _u
}

// ClearMaxPendingParents clears the value of the "max_pending_parents" field.
func (_u *RateLimitUserOverrideUpdate) ClearMaxPendingParents() *RateLimitUserOverrideUpdate {
	_u.mutation.ClearMaxPendingParents()
	return _u
}

// SetMaxPendingChildren sets the "max_pending_children" field.
func (_u *RateLimitUserOverrideUpdate) SetMaxPendingChildren(v int) *RateLimitUserOverrideUpdate {
	_u.mutation.ResetMaxPendingChildren()
	_u.mutation.SetMaxPendingChildren(v)
	return _u
}

// SetNillableMaxPendingChildren sets the "max_pending_children" field if the given value is not nil.
func (_u *RateLimitUserOverrideUpdate) SetNillableMaxPendingChildren(v *int) *RateLimitUserOverrideUpdate {
	if v != nil {
		_u.SetMaxPendingChildren(*v)
	}
	return _u
}

// AddMaxPendingChildren adds value to the "max_pending_children" field.
func (_u *RateLimitUserOverrideUpdate) AddMaxPendingChildren(v int) *RateLimitUserOverrideUpdate {
	_u.mutation.AddMaxPendingChildren(v)
	return _u
}

// ClearMaxPendingChildren clears the value of the "max_pending_children" field.
func (_u *RateLimitUserOverrideUpdate) ClearMaxPendingChildren() *RateLimitUserOverrideUpdate {
	_u.mutation.ClearMaxPendingChildren()
	return _u
}

// SetCooldownSeconds sets the "cooldown_seconds" field.
func (_u *RateLimitUserOverrideUpdate) SetCooldownSeconds(v int) *RateLimitUserOverrideUpdate {
	_u.mutation.ResetCooldownSeconds()
	_u.mutation.SetCooldownSeconds(v)
	return _u
}

// SetNillableCooldownSeconds sets the "cooldown_seconds" field if the given value is not nil.
func (_u *RateLimitUserOverrideUpdate) SetNillableCooldownSeconds(v *int) *RateLimitUserOverrideUpdate {
	if v != nil {
		_u.SetCooldownSeconds(*v)
	}
	return _u
}

// AddCooldownSeconds adds value to the "cooldown_seconds" field.
func (_u *RateLimitUserOverrideUpdate) AddCooldownSeconds(v int) *RateLimitUserOverrideUpdate {
	_u.mutation.AddCooldownSeconds(v)
	return _u
}

// ClearCooldownSeconds clears the value of the "cooldown_seconds" field.
func (_u *RateLimitUserOverrideUpdate) ClearCooldownSeconds() *RateLimitUserOverrideUpdate {
	_u.mutation.ClearCooldownSeconds()
	return _u
}

// SetReason sets the "reason" field.
func (_u *RateLimitUserOverrideUpdate) SetReason(v string) *RateLimitUserOverrideUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *RateLimitUserOverrideUpdate) SetNillableReason(v *string) *RateLimitUserOverrideUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *RateLimitUserOverrideUpdate) ClearReason() *RateLimitUserOverrideUpdate {
	_u.mutation.ClearReason()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *RateLimitUserOverrideUpdate) SetUpdatedBy(v string) *RateLimitUserOverrideUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *RateLimitUserOverrideUpdate) SetNillableUpdatedBy(v *string) *RateLimitUserOverrideUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// Mutation returns the RateLimitUserOverrideMutation object of the builder.
func (_u *RateLimitUserOverrideUpdate) Mutation() *RateLimitUserOverrideMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RateLimitUserOverrideUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RateLimitUserOverrideUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RateLimitUserOverrideUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RateLimitUserOverrideUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RateLimitUserOverrideUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ratelimituseroverride.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RateLimitUserOverrideUpdate) check() error {
	if v, ok := _u.mutation.MaxPendingParents(); ok {
		if err := ratelimituseroverride.MaxPendingParentsValidator(v); err != nil {
			return &ValidationError{Name: "max_pending_parents", err: fmt.Errorf(`ent: validator failed for field "RateLimitUserOverride.max_pending_parents": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxPendingChildren(); ok {
		if err := ratelimituseroverride.MaxPendingChildrenValidator(v); err != nil {
			return &ValidationError{Name: "max_pending_children", err: fmt.Errorf(`ent: validator failed for field "RateLimitUserOverride.max_pending_children": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CooldownSeconds(); ok {
		if err := ratelimituseroverride.CooldownSecondsValidator(v); err != nil {
			return &ValidationError{Name: "cooldown_seconds", err: fmt.Errorf(`ent: validator failed for field "RateLimitUserOverride.cooldown_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpdatedBy(); ok {
		if err := ratelimituseroverride.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "RateLimitUserOverride.updated_by": %w`, err)}
		}
	}
	return nil
}

func (_u *RateLimitUserOverrideUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ratelimituseroverride.Table, ratelimituseroverride.Columns, sqlgraph.NewFieldSpec(ratelimituseroverride.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ratelimituseroverride.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MaxPendingParents(); ok {
		_spec.SetField(ratelimituseroverride.FieldMaxPendingParents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxPendingParents(); ok {
		_spec.AddField(ratelimituseroverride.FieldMaxPendingParents, field.TypeInt, value)
	}
	if _u.mutation.MaxPendingParentsCleared() {
		_spec.ClearField(ratelimituseroverride.FieldMaxPendingParents, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxPendingChildren(); ok {
		_spec.SetField(ratelimituseroverride.FieldMaxPendingChildren, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxPendingChildren(); ok {
		_spec.AddField(ratelimituseroverride.FieldMaxPendingChildren, field.TypeInt, value)
	}
	if _u.mutation.MaxPendingChildrenCleared() {
		_spec.ClearField(ratelimituseroverride.FieldMaxPendingChildren, field.TypeInt)
	}
	if value, ok := _u.mutation.CooldownSeconds(); ok {
		_spec.SetField(ratelimituseroverride.FieldCooldownSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCooldownSeconds(); ok {
		_spec.AddField(ratelimituseroverride.FieldCooldownSeconds, field.TypeInt, value)
	}
	if _u.mutation.CooldownSecondsCleared() {
		_spec.ClearField(ratelimituseroverride.FieldCooldownSeconds, field.TypeInt)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(ratelimituseroverride.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(ratelimituseroverride.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(ratelimituseroverride.FieldUpdatedBy, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ratelimituseroverride.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RateLimitUserOverrideUpdateOne is the builder for updating a single RateLimitUserOverride entity.
type RateLimitUserOverrideUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RateLimitUserOverrideMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RateLimitUserOverrideUpdateOne) SetUpdatedAt(v time.Time) *RateLimitUserOverrideUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMaxPendingParents sets the "max_pending_parents" field.
func (_u *RateLimitUserOverrideUpdateOne) SetMaxPendingParents(v int) *RateLimitUserOverrideUpdateOne {
	_u.mutation.ResetMaxPendingParents()
	_u.mutation.SetMaxPendingParents(v)
	return _u
}

// SetNillableMaxPendingParents sets the "max_pending_parents" field if the given value is not nil.
func (_u *RateLimitUserOverrideUpdateOne) SetNillableMaxPendingParents(v *int) *RateLimitUserOverrideUpdateOne {
	if v != nil {
		_u.SetMaxPendingParents(*v)
	}
	return _u
}

// AddMaxPendingParents adds value to the "max_pending_parents" field.
func (_u *RateLimitUserOverrideUpdateOne) AddMaxPendingParents(v int) *RateLimitUserOverrideUpdateOne {
	_u.mutation.AddMaxPendingParents(v)
	return _u
}

// ClearMaxPendingParents clears the value of the "max_pending_parents" field.
func (_u *RateLimitUserOverrideUpdateOne) ClearMaxPendingParents() *RateLimitUserOverrideUpdateOne {
	_u.mutation.ClearMaxPendingParents()
	return _u
}

// SetMaxPendingChildren sets the "max_pending_children" field.
func (_u *RateLimitUserOverrideUpdateOne) SetMaxPendingChildren(v int) *RateLimitUserOverrideUpdateOne {
	_u.mutation.ResetMaxPendingChildren()
	_u.mutation.SetMaxPendingChildren(v)
	return _u
}

// SetNillableMaxPendingChildren sets the "max_pending_children" field if the given value is not nil.
func (_u *RateLimitUserOverrideUpdateOne) SetNillableMaxPendingChildren(v *int) *RateLimitUserOverrideUpdateOne {
	if v != nil {
		_u.SetMaxPendingChildren(*v)
	}
	return _u
}

// AddMaxPendingChildren adds value to the "max_pending_children" field.
func (_u *RateLimitUserOverrideUpdateOne) AddMaxPendingChildren(v int) *RateLimitUserOverrideUpdateOne {
	_u.mutation.AddMaxPendingChildren(v)
	return _u
}

// ClearMaxPendingChildren clears the value of the "max_pending_children" field.
func (_u *RateLimitUserOverrideUpdateOne) ClearMaxPendingChildren() *RateLimitUserOverrideUpdateOne {
	_u.mutation.ClearMaxPendingChildren()
	return _u
}

// SetCooldownSeconds sets the "cooldown_seconds" field.
func (_u *RateLimitUserOverrideUpdateOne) SetCooldownSeconds(v int) *RateLimitUserOverrideUpdateOne {
	_u.mutation.ResetCooldownSeconds()
	_u.mutation.SetCooldownSeconds(v)
	return _u
}

// SetNillableCooldownSeconds sets the "cooldown_seconds" field if the given value is not nil.
func (_u *RateLimitUserOverrideUpdateOne) SetNillableCooldownSeconds(v *int) *RateLimitUserOverrideUpdateOne {
	if v != nil {
		_u.SetCooldownSeconds(*v)
	}
	return _u
}

// AddCooldownSeconds adds value to the "cooldown_seconds" field.
func (_u *RateLimitUserOverrideUpdateOne) AddCooldownSeconds(v int) *RateLimitUserOverrideUpdateOne {
	_u.mutation.AddCooldownSeconds(v)
	return _u
}

// ClearCooldownSeconds clears the value of the "cooldown_seconds" field.
func (_u *RateLimitUserOverrideUpdateOne) ClearCooldownSeconds() *RateLimitUserOverrideUpdateOne {
	_u.mutation.ClearCooldownSeconds()
	return _u
}

// SetReason sets the "reason" field.
func (_u *RateLimitUserOverrideUpdateOne) SetReason(v string) *RateLimitUserOverrideUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *RateLimitUserOverrideUpdateOne) SetNillableReason(v *string) *RateLimitUserOverrideUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *RateLimitUserOverrideUpdateOne) ClearReason() *RateLimitUserOverrideUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *RateLimitUserOverrideUpdateOne) SetUpdatedBy(v string) *RateLimitUserOverrideUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *RateLimitUserOverrideUpdateOne) SetNillableUpdatedBy(v *string) *RateLimitUserOverrideUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// Mutation returns the RateLimitUserOverrideMutation object of the builder.
func (_u *RateLimitUserOverrideUpdateOne) Mutation() *RateLimitUserOverrideMutation {
	return _u.mutation
}

// Where appends a list predicates to the RateLimitUserOverrideUpdate builder.
func (_u *RateLimitUserOverrideUpdateOne) Where(ps ...predicate.RateLimitUserOverride) *RateLimitUserOverrideUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RateLimitUserOverrideUpdateOne) Select(field string, fields ...string) *RateLimitUserOverrideUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RateLimitUserOverride entity.
func (_u *RateLimitUserOverrideUpdateOne) Save(ctx context.Context) (*RateLimitUserOverride, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RateLimitUserOverrideUpdateOne) SaveX(ctx context.Context) *RateLimitUserOverride {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RateLimitUserOverrideUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RateLimitUserOverrideUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RateLimitUserOverrideUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ratelimituseroverride.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RateLimitUserOverrideUpdateOne) check() error {
	if v, ok := _u.mutation.MaxPendingParents(); ok {
		if err := ratelimituseroverride.MaxPendingParentsValidator(v); err != nil {
			return &ValidationError{Name: "max_pending_parents", err: fmt.Errorf(`ent: validator failed for field "RateLimitUserOverride.max_pending_parents": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxPendingChildren(); ok {
		if err := ratelimituseroverride.MaxPendingChildrenValidator(v); err != nil {
			return &ValidationError{Name: "max_pending_children", err: fmt.Errorf(`ent: validator failed for field "RateLimitUserOverride.max_pending_children": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CooldownSeconds(); ok {
		if err := ratelimituseroverride.CooldownSecondsValidator(v); err != nil {
			return &ValidationError{Name: "cooldown_seconds", err: fmt.Errorf(`ent: validator failed for field "RateLimitUserOverride.cooldown_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpdatedBy(); ok {
		if err := ratelimituseroverride.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "RateLimitUserOverride.updated_by": %w`, err)}
		}
	}
	return nil
}

func (_u *RateLimitUserOverrideUpdateOne) sqlSave(ctx context.Context) (_node *RateLimitUserOverride, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ratelimituseroverride.Table, ratelimituseroverride.Columns, sqlgraph.NewFieldSpec(ratelimituseroverride.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RateLimitUserOverride.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ratelimituseroverride.FieldID)
		for _, f := range fields {
			if !ratelimituseroverride.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ratelimituseroverride.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ratelimituseroverride.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MaxPendingParents(); ok {
		_spec.SetField(ratelimituseroverride.FieldMaxPendingParents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxPendingParents(); ok {
		_spec.AddField(ratelimituseroverride.FieldMaxPendingParents, field.TypeInt, value)
	}
	if _u.mutation.MaxPendingParentsCleared() {
		_spec.ClearField(ratelimituseroverride.FieldMaxPendingParents, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxPendingChildren(); ok {
		_spec.SetField(ratelimituseroverride.FieldMaxPendingChildren, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxPendingChildren(); ok {
		_spec.AddField(ratelimituseroverride.FieldMaxPendingChildren, field.TypeInt, value)
	}
	if _u.mutation.MaxPendingChildrenCleared() {
		_spec.ClearField(ratelimituseroverride.FieldMaxPendingChildren, field.TypeInt)
	}
	if value, ok := _u.mutation.CooldownSeconds(); ok {
		_spec.SetField(ratelimituseroverride.FieldCooldownSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCooldownSeconds(); ok {
		_spec.AddField(ratelimituseroverride.FieldCooldownSeconds, field.TypeInt, value)
	}
	if _u.mutation.CooldownSecondsCleared() {
		_spec.ClearField(ratelimituseroverride.FieldCooldownSeconds, field.TypeInt)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(ratelimituseroverride.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(ratelimituseroverride.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(ratelimituseroverride.FieldUpdatedBy, field.TypeString, value)
	}
	_node = &RateLimitUserOverride{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ratelimituseroverride.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
