// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"kv-shepherd.io/shepherd/ent/user"
	"kv-shepherd.io/shepherd/ent/userdirectoryprofile"
)

// UserDirectoryProfileCreate is the builder for creating a UserDirectoryProfile entity.
type UserDirectoryProfileCreate struct {
	config
	mutation *UserDirectoryProfileMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserDirectoryProfileCreate) SetCreatedAt(v time.Time) *UserDirectoryProfileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserDirectoryProfileCreate) SetNillableCreatedAt(v *time.Time) *UserDirectoryProfileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserDirectoryProfileCreate) SetUpdatedAt(v time.Time) *UserDirectoryProfileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserDirectoryProfileCreate) SetNillableUpdatedAt(v *time.Time) *UserDirectoryProfileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserDirectoryProfileCreate) SetUserID(v string) *UserDirectoryProfileCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAttributes sets the "attributes" field.
func (_c *UserDirectoryProfileCreate) SetAttributes(v map[string]interface{}) *UserDirectoryProfileCreate {
	_c.mutation.SetAttributes(v)
	return _c
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_c *UserDirectoryProfileCreate) SetLastSyncedAt(v time.Time) *UserDirectoryProfileCreate {
	_c.mutation.SetLastSyncedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *UserDirectoryProfileCreate) SetID(v string) *UserDirectoryProfileCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserDirectoryProfileCreate) SetUser(v *User) *UserDirectoryProfileCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserDirectoryProfileMutation object of the builder.
func (_c *UserDirectoryProfileCreate) Mutation() *UserDirectoryProfileMutation {
	return _c.mutation
}

// Save creates the UserDirectoryProfile in the database.
func (_c *UserDirectoryProfileCreate) Save(ctx context.Context) (*UserDirectoryProfile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserDirectoryProfileCreate) SaveX(ctx context.Context) *UserDirectoryProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserDirectoryProfileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserDirectoryProfileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserDirectoryProfileCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userdirectoryprofile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userdirectoryprofile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserDirectoryProfileCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserDirectoryProfile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserDirectoryProfile.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserDirectoryProfile.user_id"`)}
	}
	if _, ok := _c.mutation.Attributes(); !ok {
		return &ValidationError{Name: "attributes", err: errors.New(`ent: missing required field "UserDirectoryProfile.attributes"`)}
	}
	if _, ok := _c.mutation.LastSyncedAt(); !ok {
		return &ValidationError{Name: "last_synced_at", err: errors.New(`ent: missing required field "UserDirectoryProfile.last_synced_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserDirectoryProfile.user"`)}
	}
	return nil
}

func (_c *UserDirectoryProfileCreate) sqlSave(ctx context.Context) (*UserDirectoryProfile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected UserDirectoryProfile.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserDirectoryProfileCreate) createSpec() (*UserDirectoryProfile, *sqlgraph.CreateSpec) {
	var (
		_node = &UserDirectoryProfile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userdirectoryprofile.Table, sqlgraph.NewFieldSpec(userdirectoryprofile.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userdirectoryprofile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userdirectoryprofile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Attributes(); ok {
		_spec.SetField(userdirectoryprofile.FieldAttributes, field.TypeJSON, value)
		_node.Attributes = value
	}
	if value, ok := _c.mutation.LastSyncedAt(); ok {
		_spec.SetField(userdirectoryprofile.FieldLastSyncedAt, field.TypeTime, value)
		_node.LastSyncedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userdirectoryprofile.UserTable,
			Columns: []string{userdirectoryprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserDirectoryProfileCreateBulk is the builder for creating many UserDirectoryProfile entities in bulk.
type UserDirectoryProfileCreateBulk struct {
	config
	err      error
	builders []*UserDirectoryProfileCreate
}

// Save creates the UserDirectoryProfile entities in the database.
func (_c *UserDirectoryProfileCreateBulk) Save(ctx context.Context) ([]*UserDirectoryProfile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserDirectoryProfile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserDirectoryProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserDirectoryProfileCreateBulk) SaveX(ctx context.Context) []*UserDirectoryProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserDirectoryProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserDirectoryProfileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
