// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"kv-shepherd.io/shepherd/ent/vm"
	"kv-shepherd.io/shepherd/ent/vmrevision"
)

// VMRevisionCreate is the builder for creating a VMRevision entity.
type VMRevisionCreate struct {
	config
	mutation *VMRevisionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *VMRevisionCreate) SetCreatedAt(v time.Time) *VMRevisionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VMRevisionCreate) SetNillableCreatedAt(v *time.Time) *VMRevisionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetRevision sets the "revision" field.
func (_c *VMRevisionCreate) SetRevision(v int) *VMRevisionCreate {
	_c.mutation.SetRevision(v)
	return _c
}

// SetSpec sets the "spec" field.
func (_c *VMRevisionCreate) SetSpec(v map[string]interface{}) *VMRevisionCreate {
	_c.mutation.SetSpec(v)
	return _c
}

// SetChangeReason sets the "change_reason" field.
func (_c *VMRevisionCreate) SetChangeReason(v string) *VMRevisionCreate {
	_c.mutation.SetChangeReason(v)
	return _c
}

// SetNillableChangeReason sets the "change_reason" field if the given value is not nil.
func (_c *VMRevisionCreate) SetNillableChangeReason(v *string) *VMRevisionCreate {
	if v != nil {
		_c.SetChangeReason(*v)
	}
	return _c
}

// SetChangedBy sets the "changed_by" field.
func (_c *VMRevisionCreate) SetChangedBy(v string) *VMRevisionCreate {
	_c.mutation.SetChangedBy(v)
	return _c
}

// SetID sets the "id" field.
func (_c *VMRevisionCreate) SetID(v string) *VMRevisionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetVMID sets the "vm" edge to the VM entity by ID.
func (_c *VMRevisionCreate) SetVMID(id string) *VMRevisionCreate {
	_c.mutation.SetVMID(id)
	return _c
}

// SetVM sets the "vm" edge to the VM entity.
func (_c *VMRevisionCreate) SetVM(v *VM) *VMRevisionCreate {
	return _c.SetVMID(v.ID)
}

// Mutation returns the VMRevisionMutation object of the builder.
func (_c *VMRevisionCreate) Mutation() *VMRevisionMutation {
	return _c.mutation
}

// Save creates the VMRevision in the database.
func (_c *VMRevisionCreate) Save(ctx context.Context) (*VMRevision, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VMRevisionCreate) SaveX(ctx context.Context) *VMRevision {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VMRevisionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VMRevisionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VMRevisionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := vmrevision.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VMRevisionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VMRevision.created_at"`)}
	}
	if _, ok := _c.mutation.Revision(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`ent: missing required field "VMRevision.revision"`)}
	}
	if v, ok := _c.mutation.Revision(); ok {
		if err := vmrevision.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "VMRevision.revision": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChangedBy(); !ok {
		return &ValidationError{Name: "changed_by", err: errors.New(`ent: missing required field "VMRevision.changed_by"`)}
	}
	if v, ok := _c.mutation.ChangedBy(); ok {
		if err := vmrevision.ChangedByValidator(v); err != nil {
			return &ValidationError{Name: "changed_by", err: fmt.Errorf(`ent: validator failed for field "VMRevision.changed_by": %w`, err)}
		}
	}
	if len(_c.mutation.VMIDs()) == 0 {
		return &ValidationError{Name: "vm", err: errors.New(`ent: missing required edge "VMRevision.vm"`)}
	}
	return nil
}

func (_c *VMRevisionCreate) sqlSave(ctx context.Context) (*VMRevision, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected VMRevision.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VMRevisionCreate) createSpec() (*VMRevision, *sqlgraph.CreateSpec) {
	var (
		_node = &VMRevision{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(vmrevision.Table, sqlgraph.NewFieldSpec(vmrevision.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(vmrevision.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Revision(); ok {
		_spec.SetField(vmrevision.FieldRevision, field.TypeInt, value)
		_node.Revision = value
	}
	if value, ok := _c.mutation.Spec(); ok {
		_spec.SetField(vmrevision.FieldSpec, field.TypeJSON, value)
		_node.Spec = value
	}
	if value, ok := _c.mutation.ChangeReason(); ok {
		_spec.SetField(vmrevision.FieldChangeReason, field.TypeString, value)
		_node.ChangeReason = value
	}
	if value, ok := _c.mutation.ChangedBy(); ok {
		_spec.SetField(vmrevision.FieldChangedBy, field.TypeString, value)
		_node.ChangedBy = value
	}
	if nodes := _c.mutation.VMIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vmrevision.VMTable,
			Columns: []string{vmrevision.VMColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vm.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.vm_revisions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// VMRevisionCreateBulk is the builder for creating many VMRevision entities in bulk.
type VMRevisionCreateBulk struct {
	config
	err      error
	builders []*VMRevisionCreate
}

// Save creates the VMRevision entities in the database.
func (_c *VMRevisionCreateBulk) Save(ctx context.Context) ([]*VMRevision, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VMRevision, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VMRevisionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VMRevisionCreateBulk) SaveX(ctx context.Context) []*VMRevision {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VMRevisionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VMRevisionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
