// Code generated by ent, DO NOT EDIT.

package externalapprovalsystem

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the externalapprovalsystem type in the database.
	Label = "external_approval_system"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSystemType holds the string denoting the system_type field in the database.
	FieldSystemType = "system_type"
	// FieldConfig holds the string denoting the config field in the database.
	FieldConfig = "config"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// Table holds the table name of the externalapprovalsystem in the database.
	Table = "external_approval_systems"
)

// Columns holds all SQL columns for externalapprovalsystem fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldSystemType,
	FieldConfig,
	FieldEnabled,
	FieldCreatedBy,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	CreatedByValidator func(string) error
)

// SystemType defines the type for the "system_type" enum field.
type SystemType string

// SystemType values.
const (
	SystemTypeWebhook    SystemType = "webhook"
	SystemTypeJira       SystemType = "jira"
	SystemTypeServicenow SystemType = "servicenow"
	SystemTypeCustom     SystemType = "custom"
)

func (st SystemType) String() string {
	return string(st)
}

// SystemTypeValidator is a validator for the "system_type" field enum values. It is called by the builders before save.
func SystemTypeValidator(st SystemType) error {
	switch st {
	case SystemTypeWebhook, SystemTypeJira, SystemTypeServicenow, SystemTypeCustom:
		return nil
	default:
		return fmt.Errorf("externalapprovalsystem: invalid enum value for system_type field: %q", st)
	}
}

// OrderOption defines the ordering options for the ExternalApprovalSystem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySystemType orders the results by the system_type field.
func BySystemType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSystemType, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}
