// Code generated by ent, DO NOT EDIT.

package externalapprovalsystem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"kv-shepherd.io/shepherd/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldName, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldEnabled, v))
}

// WebhookURL applies equality check predicate on the "webhook_url" field. It's identical to WebhookURLEQ.
func WebhookURL(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldWebhookURL, v))
}

// TimeoutSeconds applies equality check predicate on the "timeout_seconds" field. It's identical to TimeoutSecondsEQ.
func TimeoutSeconds(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldTimeoutSeconds, v))
}

// RetryCount applies equality check predicate on the "retry_count" field. It's identical to RetryCountEQ.
func RetryCount(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldRetryCount, v))
}

// RetryBackoffSeconds applies equality check predicate on the "retry_backoff_seconds" field. It's identical to RetryBackoffSecondsEQ.
func RetryBackoffSeconds(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldRetryBackoffSeconds, v))
}

// SigningKeyCiphertext applies equality check predicate on the "signing_key_ciphertext" field. It's identical to SigningKeyCiphertextEQ.
func SigningKeyCiphertext(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldSigningKeyCiphertext, v))
}

// EncryptionKeyID applies equality check predicate on the "encryption_key_id" field. It's identical to EncryptionKeyIDEQ.
func EncryptionKeyID(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldEncryptionKeyID, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldContainsFold(FieldName, v))
}

// ProviderTypeEQ applies the EQ predicate on the "provider_type" field.
func ProviderTypeEQ(v ProviderType) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldProviderType, v))
}

// ProviderTypeNEQ applies the NEQ predicate on the "provider_type" field.
func ProviderTypeNEQ(v ProviderType) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNEQ(FieldProviderType, v))
}

// ProviderTypeIn applies the In predicate on the "provider_type" field.
func ProviderTypeIn(vs ...ProviderType) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldIn(FieldProviderType, vs...))
}

// ProviderTypeNotIn applies the NotIn predicate on the "provider_type" field.
func ProviderTypeNotIn(vs ...ProviderType) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNotIn(FieldProviderType, vs...))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNEQ(FieldEnabled, v))
}

// WebhookURLEQ applies the EQ predicate on the "webhook_url" field.
func WebhookURLEQ(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldWebhookURL, v))
}

// WebhookURLNEQ applies the NEQ predicate on the "webhook_url" field.
func WebhookURLNEQ(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNEQ(FieldWebhookURL, v))
}

// WebhookURLIn applies the In predicate on the "webhook_url" field.
func WebhookURLIn(vs ...string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldIn(FieldWebhookURL, vs...))
}

// WebhookURLNotIn applies the NotIn predicate on the "webhook_url" field.
func WebhookURLNotIn(vs ...string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNotIn(FieldWebhookURL, vs...))
}

// WebhookURLGT applies the GT predicate on the "webhook_url" field.
func WebhookURLGT(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGT(FieldWebhookURL, v))
}

// WebhookURLGTE applies the GTE predicate on the "webhook_url" field.
func WebhookURLGTE(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGTE(FieldWebhookURL, v))
}

// WebhookURLLT applies the LT predicate on the "webhook_url" field.
func WebhookURLLT(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLT(FieldWebhookURL, v))
}

// WebhookURLLTE applies the LTE predicate on the "webhook_url" field.
func WebhookURLLTE(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLTE(FieldWebhookURL, v))
}

// WebhookURLContains applies the Contains predicate on the "webhook_url" field.
func WebhookURLContains(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldContains(FieldWebhookURL, v))
}

// WebhookURLHasPrefix applies the HasPrefix predicate on the "webhook_url" field.
func WebhookURLHasPrefix(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldHasPrefix(FieldWebhookURL, v))
}

// WebhookURLHasSuffix applies the HasSuffix predicate on the "webhook_url" field.
func WebhookURLHasSuffix(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldHasSuffix(FieldWebhookURL, v))
}

// WebhookURLEqualFold applies the EqualFold predicate on the "webhook_url" field.
func WebhookURLEqualFold(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEqualFold(FieldWebhookURL, v))
}

// WebhookURLContainsFold applies the ContainsFold predicate on the "webhook_url" field.
func WebhookURLContainsFold(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldContainsFold(FieldWebhookURL, v))
}

// TimeoutSecondsEQ applies the EQ predicate on the "timeout_seconds" field.
func TimeoutSecondsEQ(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldTimeoutSeconds, v))
}

// TimeoutSecondsNEQ applies the NEQ predicate on the "timeout_seconds" field.
func TimeoutSecondsNEQ(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNEQ(FieldTimeoutSeconds, v))
}

// TimeoutSecondsIn applies the In predicate on the "timeout_seconds" field.
func TimeoutSecondsIn(vs ...int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldIn(FieldTimeoutSeconds, vs...))
}

// TimeoutSecondsNotIn applies the NotIn predicate on the "timeout_seconds" field.
func TimeoutSecondsNotIn(vs ...int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNotIn(FieldTimeoutSeconds, vs...))
}

// TimeoutSecondsGT applies the GT predicate on the "timeout_seconds" field.
func TimeoutSecondsGT(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGT(FieldTimeoutSeconds, v))
}

// TimeoutSecondsGTE applies the GTE predicate on the "timeout_seconds" field.
func TimeoutSecondsGTE(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGTE(FieldTimeoutSeconds, v))
}

// TimeoutSecondsLT applies the LT predicate on the "timeout_seconds" field.
func TimeoutSecondsLT(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLT(FieldTimeoutSeconds, v))
}

// TimeoutSecondsLTE applies the LTE predicate on the "timeout_seconds" field.
func TimeoutSecondsLTE(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLTE(FieldTimeoutSeconds, v))
}

// RetryCountEQ applies the EQ predicate on the "retry_count" field.
func RetryCountEQ(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldRetryCount, v))
}

// RetryCountNEQ applies the NEQ predicate on the "retry_count" field.
func RetryCountNEQ(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNEQ(FieldRetryCount, v))
}

// RetryCountIn applies the In predicate on the "retry_count" field.
func RetryCountIn(vs ...int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldIn(FieldRetryCount, vs...))
}

// RetryCountNotIn applies the NotIn predicate on the "retry_count" field.
func RetryCountNotIn(vs ...int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNotIn(FieldRetryCount, vs...))
}

// RetryCountGT applies the GT predicate on the "retry_count" field.
func RetryCountGT(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGT(FieldRetryCount, v))
}

// RetryCountGTE applies the GTE predicate on the "retry_count" field.
func RetryCountGTE(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGTE(FieldRetryCount, v))
}

// RetryCountLT applies the LT predicate on the "retry_count" field.
func RetryCountLT(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLT(FieldRetryCount, v))
}

// RetryCountLTE applies the LTE predicate on the "retry_count" field.
func RetryCountLTE(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLTE(FieldRetryCount, v))
}

// RetryBackoffSecondsEQ applies the EQ predicate on the "retry_backoff_seconds" field.
func RetryBackoffSecondsEQ(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldRetryBackoffSeconds, v))
}

// RetryBackoffSecondsNEQ applies the NEQ predicate on the "retry_backoff_seconds" field.
func RetryBackoffSecondsNEQ(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNEQ(FieldRetryBackoffSeconds, v))
}

// RetryBackoffSecondsIn applies the In predicate on the "retry_backoff_seconds" field.
func RetryBackoffSecondsIn(vs ...int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldIn(FieldRetryBackoffSeconds, vs...))
}

// RetryBackoffSecondsNotIn applies the NotIn predicate on the "retry_backoff_seconds" field.
func RetryBackoffSecondsNotIn(vs ...int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNotIn(FieldRetryBackoffSeconds, vs...))
}

// RetryBackoffSecondsGT applies the GT predicate on the "retry_backoff_seconds" field.
func RetryBackoffSecondsGT(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGT(FieldRetryBackoffSeconds, v))
}

// RetryBackoffSecondsGTE applies the GTE predicate on the "retry_backoff_seconds" field.
func RetryBackoffSecondsGTE(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGTE(FieldRetryBackoffSeconds, v))
}

// RetryBackoffSecondsLT applies the LT predicate on the "retry_backoff_seconds" field.
func RetryBackoffSecondsLT(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLT(FieldRetryBackoffSeconds, v))
}

// RetryBackoffSecondsLTE applies the LTE predicate on the "retry_backoff_seconds" field.
func RetryBackoffSecondsLTE(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLTE(FieldRetryBackoffSeconds, v))
}

// SigningKeyCiphertextEQ applies the EQ predicate on the "signing_key_ciphertext" field.
func SigningKeyCiphertextEQ(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldSigningKeyCiphertext, v))
}

// SigningKeyCiphertextNEQ applies the NEQ predicate on the "signing_key_ciphertext" field.
func SigningKeyCiphertextNEQ(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNEQ(FieldSigningKeyCiphertext, v))
}

// SigningKeyCiphertextIn applies the In predicate on the "signing_key_ciphertext" field.
func SigningKeyCiphertextIn(vs ...string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldIn(FieldSigningKeyCiphertext, vs...))
}

// SigningKeyCiphertextNotIn applies the NotIn predicate on the "signing_key_ciphertext" field.
func SigningKeyCiphertextNotIn(vs ...string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNotIn(FieldSigningKeyCiphertext, vs...))
}

// SigningKeyCiphertextGT applies the GT predicate on the "signing_key_ciphertext" field.
func SigningKeyCiphertextGT(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGT(FieldSigningKeyCiphertext, v))
}

// SigningKeyCiphertextGTE applies the GTE predicate on the "signing_key_ciphertext" field.
func SigningKeyCiphertextGTE(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGTE(FieldSigningKeyCiphertext, v))
}

// SigningKeyCiphertextLT applies the LT predicate on the "signing_key_ciphertext" field.
func SigningKeyCiphertextLT(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLT(FieldSigningKeyCiphertext, v))
}

// SigningKeyCiphertextLTE applies the LTE predicate on the "signing_key_ciphertext" field.
func SigningKeyCiphertextLTE(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLTE(FieldSigningKeyCiphertext, v))
}

// SigningKeyCiphertextContains applies the Contains predicate on the "signing_key_ciphertext" field.
func SigningKeyCiphertextContains(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldContains(FieldSigningKeyCiphertext, v))
}

// SigningKeyCiphertextHasPrefix applies the HasPrefix predicate on the "signing_key_ciphertext" field.
func SigningKeyCiphertextHasPrefix(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldHasPrefix(FieldSigningKeyCiphertext, v))
}

// SigningKeyCiphertextHasSuffix applies the HasSuffix predicate on the "signing_key_ciphertext" field.
func SigningKeyCiphertextHasSuffix(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldHasSuffix(FieldSigningKeyCiphertext, v))
}

// SigningKeyCiphertextIsNil applies the IsNil predicate on the "signing_key_ciphertext" field.
func SigningKeyCiphertextIsNil() predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldIsNull(FieldSigningKeyCiphertext))
}

// SigningKeyCiphertextNotNil applies the NotNil predicate on the "signing_key_ciphertext" field.
func SigningKeyCiphertextNotNil() predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNotNull(FieldSigningKeyCiphertext))
}

// SigningKeyCiphertextEqualFold applies the EqualFold predicate on the "signing_key_ciphertext" field.
func SigningKeyCiphertextEqualFold(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEqualFold(FieldSigningKeyCiphertext, v))
}

// SigningKeyCiphertextContainsFold applies the ContainsFold predicate on the "signing_key_ciphertext" field.
func SigningKeyCiphertextContainsFold(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldContainsFold(FieldSigningKeyCiphertext, v))
}

// EncryptionKeyIDEQ applies the EQ predicate on the "encryption_key_id" field.
func EncryptionKeyIDEQ(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldEncryptionKeyID, v))
}

// EncryptionKeyIDNEQ applies the NEQ predicate on the "encryption_key_id" field.
func EncryptionKeyIDNEQ(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNEQ(FieldEncryptionKeyID, v))
}

// EncryptionKeyIDIn applies the In predicate on the "encryption_key_id" field.
func EncryptionKeyIDIn(vs ...string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldIn(FieldEncryptionKeyID, vs...))
}

// EncryptionKeyIDNotIn applies the NotIn predicate on the "encryption_key_id" field.
func EncryptionKeyIDNotIn(vs ...string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNotIn(FieldEncryptionKeyID, vs...))
}

// EncryptionKeyIDGT applies the GT predicate on the "encryption_key_id" field.
func EncryptionKeyIDGT(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGT(FieldEncryptionKeyID, v))
}

// EncryptionKeyIDGTE applies the GTE predicate on the "encryption_key_id" field.
func EncryptionKeyIDGTE(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGTE(FieldEncryptionKeyID, v))
}

// EncryptionKeyIDLT applies the LT predicate on the "encryption_key_id" field.
func EncryptionKeyIDLT(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLT(FieldEncryptionKeyID, v))
}

// EncryptionKeyIDLTE applies the LTE predicate on the "encryption_key_id" field.
func EncryptionKeyIDLTE(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLTE(FieldEncryptionKeyID, v))
}

// EncryptionKeyIDContains applies the Contains predicate on the "encryption_key_id" field.
func EncryptionKeyIDContains(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldContains(FieldEncryptionKeyID, v))
}

// EncryptionKeyIDHasPrefix applies the HasPrefix predicate on the "encryption_key_id" field.
func EncryptionKeyIDHasPrefix(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldHasPrefix(FieldEncryptionKeyID, v))
}

// EncryptionKeyIDHasSuffix applies the HasSuffix predicate on the "encryption_key_id" field.
func EncryptionKeyIDHasSuffix(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldHasSuffix(FieldEncryptionKeyID, v))
}

// EncryptionKeyIDIsNil applies the IsNil predicate on the "encryption_key_id" field.
func EncryptionKeyIDIsNil() predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldIsNull(FieldEncryptionKeyID))
}

// EncryptionKeyIDNotNil applies the NotNil predicate on the "encryption_key_id" field.
func EncryptionKeyIDNotNil() predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNotNull(FieldEncryptionKeyID))
}

// EncryptionKeyIDEqualFold applies the EqualFold predicate on the "encryption_key_id" field.
func EncryptionKeyIDEqualFold(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEqualFold(FieldEncryptionKeyID, v))
}

// EncryptionKeyIDContainsFold applies the ContainsFold predicate on the "encryption_key_id" field.
func EncryptionKeyIDContainsFold(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldContainsFold(FieldEncryptionKeyID, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldContainsFold(FieldCreatedBy, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ExternalApprovalSystem) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ExternalApprovalSystem) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ExternalApprovalSystem) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.NotPredicates(p))
}
