// Code generated by ent, DO NOT EDIT.

package externalapprovalsystem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"kv-shepherd.io/shepherd/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldName, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldEnabled, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldContainsFold(FieldName, v))
}

// SystemTypeEQ applies the EQ predicate on the "system_type" field.
func SystemTypeEQ(v SystemType) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldSystemType, v))
}

// SystemTypeNEQ applies the NEQ predicate on the "system_type" field.
func SystemTypeNEQ(v SystemType) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNEQ(FieldSystemType, v))
}

// SystemTypeIn applies the In predicate on the "system_type" field.
func SystemTypeIn(vs ...SystemType) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldIn(FieldSystemType, vs...))
}

// SystemTypeNotIn applies the NotIn predicate on the "system_type" field.
func SystemTypeNotIn(vs ...SystemType) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNotIn(FieldSystemType, vs...))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.FieldContainsFold(FieldCreatedBy, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ExternalApprovalSystem) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ExternalApprovalSystem) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ExternalApprovalSystem) predicate.ExternalApprovalSystem {
	return predicate.ExternalApprovalSystem(sql.NotPredicates(p))
}
